// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Account proof envelope returned by `eth_getBalance` /
 * `eth_getStorageAt` / `lyth_registryStateProof`.
 *
 * `value` is the raw quantity (or 32-byte word for storage) as returned
 * by the chain. `state_root` is the trie root the proof is verified
 * against. `proof` is `null` when the chain provider could not produce
 * an inclusion proof for this slot at the requested block.
 */
export type AccountProofResponse = {
/**
 * `0x`-hex value (balance, storage word, or peer id depending on
 * the calling method).
 */
value: string,
/**
 * State-root hex the proof verifies against.
 */
state_root: string,
/**
 * Block height the proof was generated against.
 */
block_number: bigint,
/**
 * Inclusion proof envelope, omitted when the chain didn't produce
 * one. The shape is intentionally opaque at this layer — callers
 * that need to verify the proof bring an internal state crate in
 * directly.
 */
proof?: unknown | null, };
