// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `lyth_getAccountPolicy` response.
 */
export type AccountPolicy = {
/**
 * Policy mode label — `"public"`, `"stealth"`, `"confidential"`,
 * `"shielded"`.
 */
mode: string,
/**
 * Whether the account accepts shielded transfers.
 */
allowShielded: boolean,
/**
 * Whether the account accepts confidential transfers.
 */
allowConfidential: boolean,
/**
 * Whether the account accepts stealth payments.
 */
acceptStealth: boolean,
/**
 * Whether the account requires originator proof.
 */
requireOriginatorProof: boolean,
/**
 * Whether the account requires allowlist proof.
 */
requireAllowlistProof: boolean,
/**
 * Raw flag word, `0x`-hex two-digit byte.
 */
flags: string,
/**
 * `true` when the account has explicitly set policy bits.
 */
explicit: boolean, };
