// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressActivityKindRetention } from "./AddressActivityKindRetention.js";

/**
 * `lyth_addressActivityKind` response.
 */
export type AddressActivityKindResponse = {
/**
 * Response schema version.
 */
schemaVersion: number,
/**
 * Queried address.
 */
address: string,
/**
 * `found`, `not_found`, `indexer_disabled`, `pruned`, `private`,
 * or a forward-compatible node-supplied string.
 */
kind: string,
/**
 * Retention metadata when the activity window was pruned.
 */
retention?: AddressActivityKindRetention, };
