// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Address-label row surfaced by `lyth_getAddressLabel`.
 */
export type AddressLabelRecord = {
/**
 * Labeled address.
 */
address: string,
/**
 * Lowercase category name, e.g. `foundation`, `exchange`, `bridge`, `treasury`, `contract`, `operator`.
 */
category: string,
/**
 * Optional human-readable display name.
 */
displayName: string | null,
/**
 * Block height the label was last asserted at.
 */
updatedAtBlock: bigint,
};
