// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressActivityArchiveRedirect } from "./AddressActivityArchiveRedirect.js";

/**
 * Retention bounds returned by `lyth_addressActivityKind`.
 */
export type AddressActivityKindRetention = {
/**
 * Earliest retained block for indexed activity.
 */
earliestRetained: bigint,
/**
 * Optional archive redirect hint.
 */
archiveRedirect?: AddressActivityArchiveRedirect, };
