// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Retention metadata returned by `lyth_addressActivityKind` for
 * pruned address activity windows.
 */
export type AddressActivityArchiveRedirect = {
/**
 * Human-readable archival hint supplied by the node.
 */
hint: string, };
