// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reputation category scope returned by `lyth_agentReputation`.
 */
export type AgentReputationCategoryScope = "global" | "category";
