// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One reputation accumulator row returned by `lyth_agentReputation`.
 */
export type AgentReputationRecord = {
/**
 * Provider user address (`mono1...` bech32m).
 */
provider: string,
/**
 * Reputation category id.
 */
categoryId: number,
/**
 * Block height that last updated this record.
 */
blockHeight: number,
/**
 * Sum of speed scores multiplied by 10.
 */
speedSumX10: number,
/**
 * Sum of quality scores multiplied by 10.
 */
qualitySumX10: number,
/**
 * Sum of communication scores multiplied by 10.
 */
communicationSumX10: number,
/**
 * Sum of accuracy scores multiplied by 10.
 */
accuracySumX10: number,
/**
 * Number of samples included in the accumulators.
 */
sampleCount: number,
/**
 * Average speed score multiplied by 10.
 */
avgSpeedX10: number,
/**
 * Average quality score multiplied by 10.
 */
avgQualityX10: number,
/**
 * Average communication score multiplied by 10.
 */
avgCommunicationX10: number,
/**
 * Average accuracy score multiplied by 10.
 */
avgAccuracyX10: number, };
