// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentReputationCategoryScope } from "./AgentReputationCategoryScope.js";
import type { AgentReputationRecord } from "./AgentReputationRecord.js";

/**
 * `lyth_agentReputation` response.
 */
export type AgentReputationResponse = {
/**
 * Response schema version.
 */
schemaVersion: number,
/**
 * Queried provider user address (`mono1...` bech32m).
 */
provider: string,
/**
 * Queried category id.
 */
categoryId: number,
/**
 * Whether the node resolved the global or category-specific scope.
 */
categoryScope: AgentReputationCategoryScope,
/**
 * Reputation row, or `null` when no row exists for the provider/category.
 */
record: AgentReputationRecord | null, };
