// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `lyth_getAssetPolicy` response.
 */
export type AssetPolicy = {
/**
 * Policy mode label.
 */
mode: string,
/**
 * Whether the asset allows shielded transfers.
 */
allowShielded: boolean,
/**
 * Whether the asset allows confidential transfers.
 */
allowConfidential: boolean,
/**
 * Whether the asset allows stealth transfers.
 */
allowStealth: boolean,
/**
 * Whether the asset allows transparent transfers.
 */
allowTransparent: boolean,
/**
 * KYC requirement bit.
 */
requireKyc: boolean,
/**
 * Raw levels byte, `0x`-hex two-digit.
 */
levels: string,
/**
 * `true` when the asset has explicitly set policy.
 */
explicit: boolean, };
