// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Block header surfaced via `eth_getBlockByNumber` / `eth_getBlockByHash`.
 *
 * The v4.1 SDK shape exposes execution-unit terminology. Legacy node
 * payloads that still return `gas_used` / `gas_limit` decode through
 * serde aliases so callers can upgrade the SDK before every node RPC
 * response has been regenerated.
 */
export type BlockHeader = {
/**
 * Block number (height).
 */
number: bigint,
/**
 * Block hash (32 bytes hex).
 */
hash: string,
/**
 * Parent block hash.
 */
parent_hash: string,
/**
 * State-root commitment.
 */
state_root: string,
/**
 * UNIX seconds.
 */
timestamp: bigint,
/**
 * Total execution units consumed.
 */
executionUnitsUsed: bigint,
/**
 * Block execution-unit limit.
 */
executionUnitLimit: bigint, };
