// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * JSON-RPC block tag. Use [`BlockSelector`] when sending to the wire; passive
 * compatibility reads still use the `eth_*` block-argument shape.
 */
export type BlockTag = "latest" | "earliest" | "finalized" | "safe" | "pending";
