// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * EVM block tag. Use [`BlockSelector`] when sending to the wire — this
 * is the strongly-typed half of an `eth_*` block argument.
 */
export type BlockTag = "latest" | "earliest" | "finalized" | "safe" | "pending";
