// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Block header surfaced via `eth_getBlockByNumber` / `eth_getBlockByHash`.
 *
 * Field naming mirrors the on-wire shape — fields use snake_case in
 * the v0.0.1 server. A future server version may upgrade to camelCase;
 * when that happens we add a serde alias.
 */
export type BlockHeader = { 
/**
 * Block number (height).
 */
number: bigint, 
/**
 * Block hash (32 bytes hex).
 */
hash: string, 
/**
 * Parent block hash.
 */
parent_hash: string, 
/**
 * State-root commitment.
 */
state_root: string, 
/**
 * UNIX seconds.
 */
timestamp: bigint, 
/**
 * Total gas consumed.
 */
gas_used: bigint, 
/**
 * Block gas limit.
 */
gas_limit: bigint, };
