// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Round certificate response used by the certificate RPCs.
 */
export type BlsCertificateResponse = {
/**
 * Round at which the certificate sealed.
 */
round: bigint,
/**
 * `0x`-prefixed aggregate BLS signature.
 */
signature: string,
/**
 * Signer-set bitmap as `0x`-hex bytes.
 */
signers_bitmap: string,
/**
 * Operator indices decoded from the signer bitmap.
 */
signer_indices: Array<number>,
/**
 * Number of signing operators.
 */
signer_count: number, };
