// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeRouteCatalogueRoute } from "./BridgeRouteCatalogueRoute.js";

/**
 * Bridge route catalogue payload accepted by `mono-core` CLI imports.
 */
export type BridgeRouteCatalogue = {
/**
 * Route rows to import. The CLI also accepts a raw array; SDK exports use this envelope.
 */
routes: Array<BridgeRouteCatalogueRoute>, };
