// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Source metadata returned by `lyth_bridgeRoutes` and `/api/v1/bridge/routes`.
 */
export type BridgeRoutesSource = {
/**
 * Address whose indexed balances were used for discovery, when supplied.
 */
address?: string | null,
/**
 * Number of catalogue route disclosures returned.
 */
routeCount: number,
/**
 * Whether the node exposes a global route index independent of address rows.
 */
globalRouteIndexAvailable: boolean,
/**
 * Human-readable source of the route disclosure catalogue.
 */
routeDisclosureSource: string, };
