// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mono-side administrative control over route configuration.
 */
export type BridgeAdminControl = "none" | "consensusOnly" | "operatorKey" | "unknown";
