// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Risk tier assigned to an assessed route.
 */
export type BridgeRiskTier = "low" | "medium" | "high" | "blocked";
