// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-asset drain rate-limit + circuit-breaker state (MB-2).
 *
 * Mirrors the `TAG_DRAIN_CAP` (`0x26`) family in the chain bridge
 * storage. `cap_per_window == "0"` disables the breaker for the
 * `(bridge, asset)` pair. `drained` is the running total for the
 * active window; `remaining` is the SDK-computed `cap - drained`
 * floored at zero.
 */
export type BridgeDrainCap = {
/**
 * Maximum aggregate drain per rolling window (`uint256` decimal
 * string); `"0"` disables the breaker.
 */
capPerWindow: string,
/**
 * Window length in Protocore blocks.
 */
windowBlocks: string,
/**
 * `block_number / window_blocks` recorded at the last drain.
 */
currentBucket: string,
/**
 * Running drained total for the active window (`uint256` decimal
 * string).
 */
drained: string,
/**
 * SDK-computed `cap_per_window - drained`, floored at `0`
 * (`uint256` decimal string). `null` when the cap is disabled.
 */
remaining?: string | null, };
