// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeRouteAssessment } from "./BridgeRouteAssessment.js";
import type { BridgeRouteDisclosure } from "./BridgeRouteDisclosure.js";

/**
 * One disclosed route assessed against a concrete bridge transfer intent.
 */
export type BridgeRouteCandidate = {
/**
 * Disclosure supplied by RPC/API or the caller.
 */
route: BridgeRouteDisclosure,
/**
 * v4.1 route-floor assessment independent of this transfer.
 */
assessment: BridgeRouteAssessment,
/**
 * Whether this route can be selected for the transfer intent.
 */
eligible: boolean,
/**
 * Candidate score copied from the route assessment.
 */
score: number,
/**
 * Hard failures for this candidate, including intent mismatches.
 */
blockedReasons: Array<string>,
/**
 * Non-blocking route warnings to surface to users.
 */
warnings: Array<string>, };
