// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeRouteCandidate } from "./BridgeRouteCandidate.js";
import type { BridgeTransferRequest } from "./BridgeTransferRequest.js";

/**
 * Closed bridge-route selection result for a transfer intent.
 */
export type BridgeRouteSelection = {
/**
 * Concrete request when one route satisfied the intent and floors.
 */
selected: BridgeTransferRequest | null,
/**
 * All supplied route disclosures assessed for this intent.
 */
candidates: Array<BridgeRouteCandidate>,
/**
 * Selection-level failures. Empty when `selected` is present.
 */
blockedReasons: Array<string>, };
