// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeRiskTier } from "./BridgeRiskTier.js";

/**
 * Deterministic v4.1 bridge-floor assessment for one route.
 */
export type BridgeRouteAssessment = {
/**
 * Route id copied from the disclosure.
 */
routeId: string,
/**
 * Whether the route satisfies the required floors.
 */
accepted: boolean,
/**
 * Deterministic score in the range `0..=100`; blocked routes score `0`.
 */
score: number,
/**
 * Coarse risk tier for wallet display and policy routing.
 */
riskTier: BridgeRiskTier,
/**
 * Hard floor failures.
 */
blockedReasons: Array<string>,
/**
 * Non-blocking disclosures that should still be shown to users.
 */
warnings: Array<string>, };
