// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeRouteDisclosure } from "./BridgeRouteDisclosure.js";
import type { BridgeRouteSelection } from "./BridgeRouteSelection.js";
import type { BridgeRoutesSource } from "./BridgeRoutesSource.js";

/**
 * Response for `lyth_bridgeRoutes` and `/api/v1/bridge/routes`.
 */
export type BridgeRoutesResponse = {
/**
 * Closed route-selection result used as the readiness input.
 */
selection: BridgeRouteSelection,
/**
 * True when a route was selected from the supplied disclosures.
 */
routeSelectionReady: boolean,
/**
 * True only if the API returns real quote fields.
 */
quoteReady: boolean,
/**
 * True only if the API returns real submit fields.
 */
submitReady: boolean,
/**
 * Hard failures for route, quote, or submit readiness.
 */
blockedReasons: Array<string>,
/**
 * Non-blocking warnings copied from the selected route, when present.
 */
warnings: Array<string>,
/**
 * Raw route catalogue returned by discovery.
 */
routes?: Array<BridgeRouteDisclosure> | null,
/**
 * Compatibility alias emitted by `mono-core` for address-profile parity.
 */
bridgeRouteDisclosures?: Array<BridgeRouteDisclosure> | null,
/**
 * Node/API metadata describing where the catalogue was sourced from.
 */
source?: BridgeRoutesSource | null, };
