// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeAdminControl } from "./BridgeAdminControl.js";
import type { BridgeCircuitBreakerState } from "./BridgeCircuitBreakerState.js";
import type { BridgeVerifierDisclosure } from "./BridgeVerifierDisclosure.js";

/**
 * Caller-supplied third-party bridge route disclosure.
 */
export type BridgeRouteDisclosure = {
/**
 * Stable caller-local route id.
 */
routeId: string,
/**
 * Third-party bridge or bridge family name.
 */
bridge: string,
/**
 * Asset symbol or canonical asset id shown to users.
 */
asset: string,
/**
 * Source chain/user-facing origin label.
 */
sourceChain: string,
/**
 * Destination chain/user-facing destination label.
 */
destinationChain: string,
/**
 * Verifier-set disclosure.
 */
verifier: BridgeVerifierDisclosure,
/**
 * Per-window route drain cap as a decimal atomic-unit string.
 */
drainCapAtomic: string,
/**
 * Finality delay before the route should be treated as settled.
 */
finalityBlocks: number,
/**
 * Route-specific cooldown before reductions or resumed flow are trusted.
 */
cooldownSeconds: number,
/**
 * Mono-side administrative posture.
 */
adminControl: BridgeAdminControl,
/**
 * Circuit-breaker posture.
 */
circuitBreaker: BridgeCircuitBreakerState,
/**
 * Slashable/insured coverage ceiling as a decimal atomic-unit string.
 */
insuranceAtomic: string,
/**
 * Optional last incident date in `YYYY-MM-DD` form.
 */
lastIncidentDate?: string | null, };
