// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Route circuit-breaker state.
 */
export type BridgeCircuitBreakerState = "armed" | "paused" | "disabled" | "unknown";
