// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Verifier-set disclosure for a third-party bridge route.
 */
export type BridgeVerifierDisclosure = {
/**
 * Human-readable verifier model, e.g. `CCIP DON`.
 */
model: string,
/**
 * Number of independent verifier participants.
 */
participantCount: number,
/**
 * Minimum approvals needed to release or verify a message.
 */
threshold: number, };
