// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeRouteAssessment } from "./BridgeRouteAssessment.js";
import type { BridgeRouteDisclosure } from "./BridgeRouteDisclosure.js";
import type { BridgeTransferIntent } from "./BridgeTransferIntent.js";

/**
 * Concrete bridge request after a route has been selected.
 */
export type BridgeTransferRequest = {
/**
 * Original transfer intent.
 */
intent: BridgeTransferIntent,
/**
 * Selected route disclosure.
 */
route: BridgeRouteDisclosure,
/**
 * Assessment that justified selecting the route.
 */
assessment: BridgeRouteAssessment, };
