// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wallet/policy transfer intent for selecting among disclosed bridge routes.
 */
export type BridgeTransferIntent = {
/**
 * Asset symbol or canonical asset id the route disclosure must match.
 */
asset: string,
/**
 * Transfer amount as a decimal atomic-unit string.
 */
amountAtomic: string,
/**
 * Source chain/user-facing origin label the route disclosure must match.
 */
sourceChain: string,
/**
 * Destination chain/user-facing destination label the disclosure must match.
 */
destinationChain: string,
/**
 * Recipient address or account identifier understood by the selected route.
 */
recipient: string,
/**
 * Optional sender address/account identifier for wallet display or policy logs.
 */
sender?: string | null,
/**
 * Optional allow-list of route ids a wallet/policy is willing to use.
 */
allowedRouteIds?: Array<string> | null,
/**
 * Optional minimum route score in `0..=100`.
 */
minimumScore?: number | null,
/**
 * Optional maximum acceptable finality delay.
 */
maxFinalityBlocks?: number | null,
/**
 * Optional maximum acceptable cooldown.
 */
maxCooldownSeconds?: number | null, };
