// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeDrainCap } from "./BridgeDrainCap.js";

/**
 * Bridge route circuit-breaker + resume-cooldown health (MB-2).
 *
 * Mirrors the bridge-record fields `PAUSED_AT_BLOCK` (`0x13`),
 * `RESUME_COOLDOWN_BLOCKS` (`0x12`), `ROUTE_FINALITY_BLOCKS` (`0x14`),
 * and `ADMIN_LOCKED_AT_BLOCK` (`0x11`) plus the per-asset drain cap.
 * `paused` is derived from `paused_at != 0`.
 */
export type BridgeBreakerState = {
/**
 * Bridge id the breaker state belongs to (`0x` 32 bytes).
 */
bridgeId: string,
/**
 * `true` when the route is in a recorded pause window
 * (`paused_at != 0`).
 */
paused: boolean,
/**
 * Protocore block at which the current pause was committed; `0`
 * when not paused.
 */
pausedAt: string,
/**
 * Cooldown blocks that must elapse after a pause before
 * `unpauseBridge` can resume value-moving paths.
 */
resumeCooldownBlocks: string,
/**
 * Route-specific foreign-chain finality depth.
 */
routeFinalityBlocks: string,
/**
 * Block at which mutable route config was frozen; `0` = unlocked.
 */
adminLockedAtBlock: string,
/**
 * Per-asset drain rate-limit + breaker counters, when a cap is set.
 */
drainCap?: BridgeDrainCap | null, };
