// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeRouteDisclosure } from "./BridgeRouteDisclosure.js";
import type { BridgeTransferIntent } from "./BridgeTransferIntent.js";

/**
 * Request body for route-selection/readiness over supplied live disclosures.
 */
export type BridgeRoutesRequest = {
/**
 * Transfer intent to evaluate.
 */
intent: BridgeTransferIntent,
/**
 * Live route disclosures supplied by the node/API/caller.
 */
routeDisclosures: Array<BridgeRouteDisclosure>, };
