// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeAdminControl } from "./BridgeAdminControl.js";
import type { BridgeCircuitBreakerState } from "./BridgeCircuitBreakerState.js";
import type { BridgeVerifierDisclosure } from "./BridgeVerifierDisclosure.js";

/**
 * One trusted bridge route import row.
 */
export type BridgeRouteCatalogueRoute = {
/**
 * Native token id as 32-byte `0x` hex.
 */
tokenId: string,
/**
 * Stable caller/local route id, unique per token id.
 */
routeId: string,
/**
 * Bridge id as 32-byte `0x` hex.
 */
bridgeId: string,
/**
 * Wrapped asset address as 20-byte `0x` hex.
 */
wrappedAsset: string,
/**
 * Third-party bridge or bridge family name.
 */
bridge: string,
/**
 * Asset symbol or canonical asset id shown to users.
 */
asset: string,
/**
 * Fee token required by the route, e.g. `LINK` for CCIP.
 */
feeToken: string,
/**
 * Source chain/user-facing origin label.
 */
sourceChain: string,
/**
 * Destination chain/user-facing destination label.
 */
destinationChain: string,
/**
 * Verifier-set disclosure.
 */
verifier: BridgeVerifierDisclosure,
/**
 * Per-window route drain cap as a decimal atomic-unit string.
 */
drainCapAtomic: string,
/**
 * Finality delay before the route should be treated as settled.
 */
finalityBlocks: number,
/**
 * Route-specific cooldown before reductions or resumed flow are trusted.
 */
cooldownSeconds: number,
/**
 * Mono-side administrative posture.
 */
adminControl: BridgeAdminControl,
/**
 * Circuit-breaker posture.
 */
circuitBreaker: BridgeCircuitBreakerState,
/**
 * Slashable/insured coverage ceiling as a decimal atomic-unit string.
 */
insuranceAtomic: string,
/**
 * Last row update block observed by the importer.
 */
updatedAtBlock: number,
/**
 * Optional last incident date in `YYYY-MM-DD` form.
 */
lastIncidentDate?: string | null, };
