// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Validation report for a trusted bridge route catalogue import payload.
 */
export type BridgeRouteCatalogueValidation = {
/**
 * True when the payload is acceptable for the mono-core CLI import shape.
 */
accepted: boolean,
/**
 * Number of route rows present in the normalized catalogue.
 */
routeCount: number,
/**
 * Import-shape failures, including per-route field names.
 */
blockedReasons: Array<string>, };
