// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeRouteSelection } from "./BridgeRouteSelection.js";

/**
 * SDK-only readiness report for the quote/submit boundary.
 *
 * The SDK can deterministically verify route-selection readiness from
 * caller-supplied disclosures. It cannot produce a live third-party bridge
 * quote or submit payload until `mono-core` exposes the corresponding
 * API/runtime primitive.
 */
export type BridgeQuoteSubmitReadiness = {
/**
 * Closed route-selection result used as the readiness input.
 */
selection: BridgeRouteSelection,
/**
 * True when a route was selected from the supplied disclosures.
 */
routeSelectionReady: boolean,
/**
 * True only once a live quote API/runtime primitive is available.
 */
quoteReady: boolean,
/**
 * True only once a live submit API/runtime primitive is available.
 */
submitReady: boolean,
/**
 * Hard failures for quote/submit readiness.
 */
blockedReasons: Array<string>,
/**
 * Non-blocking warnings copied from the selected route, when present.
 */
warnings: Array<string>, };
