// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Argument shape for `eth_call` / `eth_estimateGas`.
 *
 * Every field is optional — the chain rejects payloads that omit
 * required fields with an `InvalidParams` error.
 */
export type CallRequest = {
/**
 * Source address.
 */
from?: string,
/**
 * Destination address. `None` is interpreted as contract
 * creation by the chain.
 */
to?: string,
/**
 * Execution-unit limit.
 */
gas?: string,
/**
 * Fee per execution unit on legacy / non-EIP-1559 paths.
 */
gasPrice?: string,
/**
 * Native value to transfer, in lythoshi.
 */
value?: string,
/**
 * Calldata (`data` is canonical; chains accept `input` as alias).
 */
data?: string, };
