// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityDescriptor } from "./CapabilityDescriptor.js";
import type { NativeModuleForwarderDescriptor } from "./NativeModuleForwarderDescriptor.js";

/**
 * `lyth_capabilities` response.
 */
export type CapabilitiesResponse = {
/**
 * Block height sampled by the node.
 */
blockNumber: bigint,
/**
 * Address-keyed capability map.
 */
capabilities: { [key in string]?: CapabilityDescriptor },
/**
 * Native module forwarder deployments keyed by native module name.
 */
nativeModuleForwarders: { [key in string]?: Array<NativeModuleForwarderDescriptor> }, };
