// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in the `lyth_capabilities` keyed capability map.
 */
export type CapabilityDescriptor = {
/**
 * 20-byte precompile address, `0x`-hex.
 */
address: string,
/**
 * Stable capability id from the milestone registry.
 */
capabilityId: string,
/**
 * Human-readable capability/precompile name.
 */
capabilityName: string,
/**
 * Gate class: `gateable`, `non-gateable`, or `retired-rejecting`.
 */
kind: string,
/**
 * Whether the capability is currently dispatchable.
 */
active: boolean,
/**
 * Height of the milestone that activated this capability, when any.
 */
activationHeight: bigint | null, };
