// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityDescriptor } from "./CapabilityDescriptor.js";
import type { NativeModuleForwarderDescriptor } from "./NativeModuleForwarderDescriptor.js";
import type { RuntimeFeatureGate } from "./RuntimeFeatureGate.js";

/**
 * `lyth_capabilities` response.
 */
export type CapabilitiesResponse = {
/**
 * Block height sampled by the node.
 */
blockNumber: bigint,
/**
 * Address-keyed capability map.
 */
capabilities: { [key in string]?: CapabilityDescriptor },
/**
 * Native module forwarder deployments keyed by native module name.
 */
nativeModuleForwarders: { [key in string]?: Array<NativeModuleForwarderDescriptor> },
/**
 * Runtime-feature gates that are not bound to a precompile address —
 * milestone-folded execution dials — keyed by a stable feature id (e.g.
 * `mrv_app_contract_parity`). Surfaced under the `lyth_capabilities`
 * `runtimeFeatures` map, a sibling to the address-keyed `capabilities`
 * map. Empty/absent on older nodes that predate the map; a missing entry
 * reads as inactive (forward-compatible default).
 */
runtimeFeatures: { [key in string]?: RuntimeFeatureGate }, };
