// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One signature row in `lyth_getLatestCheckpoint`.
 */
export type CheckpointRecord = {
/**
 * Block height the checkpoint commits to.
 */
blockHeight: bigint,
/**
 * State-root commitment at the checkpointed block.
 */
stateRoot: string,
/**
 * Hex-encoded ML-DSA-65 signer public key.
 */
signerPubkeyHex: string,
/**
 * Hex-encoded ML-DSA-65 signature.
 */
signatureHex: string, };
