// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Market metadata returned inside `lyth_clobMarket`.
 */
export type ClobMarketRecord = {
/**
 * Base token id.
 */
baseToken: string,
/**
 * Quote token id.
 */
quoteToken: string,
/**
 * Best bid price as a decimal string.
 */
bestBidPrice: string,
/**
 * Best ask price as a decimal string.
 */
bestAskPrice: string,
/**
 * Last trade price as a decimal string.
 */
lastTradePrice: string,
/**
 * Total traded base volume as a decimal string.
 */
totalVolumeBase: string,
/**
 * Taker fee in basis points.
 */
takerFeeBps: number,
/**
 * Tick size as a decimal string.
 */
tickSize: string,
/**
 * Lot size as a decimal string.
 */
lotSize: string,
/**
 * Minimum notional as a decimal string.
 */
minNotional: string,
/**
 * Whether the market is registered on-chain.
 */
isRegistered: boolean,
/**
 * Registration block.
 */
registeredAtBlock: bigint, };
