// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClobMarketRecord } from "./ClobMarketRecord.js";

/**
 * `lyth_clobMarket` response.
 */
export type ClobMarketResponse = {
/**
 * Response schema version.
 */
schemaVersion: number,
/**
 * Queried market id.
 */
marketId: string,
/**
 * Market metadata, or `null` when the market is not found.
 */
market: ClobMarketRecord | null, };
