// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClusterResignationRow } from "./ClusterResignationRow.js";

/**
 * `lyth_getClusterResignations` response.
 */
export type ClusterResignationsResponse = {
/**
 * Rows matching the requested filter.
 */
rows: Array<ClusterResignationRow>, };
