// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row from `lyth_getClusterResignations`.
 */
export type ClusterResignationRow = {
/**
 * `0x`-prefixed 48-byte BLS-G1 operator public key.
 */
operator: string,
/**
 * `wire_pending`, `pending`, or `applied`.
 */
status: string,
/**
 * Submitted-at block height, absent for wire-pending rows.
 */
submitted_at_height?: bigint,
/**
 * Effective-at block height, absent for wire-pending rows.
 */
effective_at_height?: bigint,
/**
 * Operator-set resignation nonce.
 */
nonce: bigint,
/**
 * Whether the expedited path was honored.
 */
expedited: boolean, };
