// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `lyth_getClusterDelegators` response.
 */
export type ClusterDelegatorsResponse = { 
/**
 * Queried cluster id.
 */
cluster: number, 
/**
 * Delegator wallet addresses.
 */
delegators: Array<string>, 
/**
 * Number of delegator slots scanned by the node.
 */
count: number, 
/**
 * Block selector echoed by the node.
 */
block: unknown, };
