// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `getClusterDiversity` view (PF-6).
 *
 * Mirrors the `(uint16 score, uint16 asnVariance, uint16 geoVariance,
 * uint16 hostingSpread)` return tuple. `score` is the unweighted mean
 * of the three breakdown terms; every field is in `0..=10000` basis
 * points.
 */
export type ClusterDiversity = {
/**
 * Headline diversity score (`0..=10000`).
 */
score: number,
/**
 * Normalised ASN-distribution entropy (`0..=10000`).
 */
asnVariance: number,
/**
 * Normalised country-distribution entropy (`0..=10000`).
 */
geoVariance: number,
/**
 * Normalised hosting-class-distribution entropy (`0..=10000`).
 */
hostingSpread: number, };
