// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Decoded `ClusterFormed(uint32,uint64,address,bytes)` event (MB-5).
 *
 * Mirrors `node-registry::events::CLUSTER_FORMED`. `operator_roster`
 * is the concatenation of the cluster members' compressed 48-byte BLS
 * pubkeys (`0x`-prefixed hex). The `anchor_address` is the cluster's
 * primary network anchor (Law §7.13) as `0x`-prefixed 20-byte hex.
 */
export type ClusterFormedEvent = {
/**
 * Cluster identifier (indexed topic 1).
 */
clusterId: number,
/**
 * Activation epoch (indexed topic 2).
 */
effectiveEpoch: bigint,
/**
 * Primary anchor address (`0x` 20 bytes).
 */
anchorAddress: string,
/**
 * Concatenated legacy 48-byte cluster-member pubkeys (`0x` hex).
 */
operatorRoster: string, };
