// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `lyth_getClusterEntity` response.
 */
export type ClusterEntityResponse = { 
/**
 * Queried cluster id.
 */
cluster: number, 
/**
 * Entity label, e.g. `"independent"` or `"mono-labs"`.
 */
entity: string, 
/**
 * Raw entity enum discriminant.
 */
entityCode: number, 
/**
 * Block selector echoed by the node.
 */
block: unknown, };
