// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parent vertex row returned by `lyth_dagParents`.
 */
export type DagParent = {
/**
 * Parent vertex hash.
 */
vertexHash: string,
/**
 * Parent round.
 */
round: bigint, };
