// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DagParent } from "./DagParent.js";

/**
 * `lyth_dagParents` response.
 */
export type DagParentsResponse = {
/**
 * Response schema version.
 */
schemaVersion: number,
/**
 * Queried round.
 */
round: bigint,
/**
 * Parent rows, or `null` when the round has no retained DAG data.
 */
parents: Array<DagParent> | null, };
