// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `lyth_syncStatus` DAG-sync driver snapshot.
 */
export type DagSyncStatus = { 
/**
 * Driver state: `idle`, `probing`, `catching`, or `synced`.
 */
state: string, 
/**
 * Local anchor frontier round.
 */
localRound: bigint, 
/**
 * Highest peer committed round observed.
 */
peerMaxRound: bigint, 
/**
 * `peerMaxRound - localRound`, saturating at zero.
 */
lag: bigint, };
