// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecodeTxLog } from "./DecodeTxLog.js";
import type { DecodeTxPqAttestation } from "./DecodeTxPqAttestation.js";

/**
 * `lyth_decodeTx` response.
 */
export type DecodeTxResponse = {
/**
 * Transaction hash.
 */
txHash: string,
/**
 * Containing block hash.
 */
blockHash: string,
/**
 * Containing block number.
 */
blockNumber: bigint,
/**
 * Transaction index within the block.
 */
txIndex: number,
/**
 * Sender address.
 */
from: string,
/**
 * Recipient address, or `null` for contract creation.
 */
to: string | null,
/**
 * Transferred value as a hex quantity.
 */
value: string,
/**
 * Sender nonce.
 */
nonce: bigint,
/**
 * Gas limit.
 */
gasLimit: bigint,
/**
 * Max fee per gas as a hex quantity.
 */
maxFeePerGas: string,
/**
 * Max priority fee per gas as a hex quantity.
 */
maxPriorityFeePerGas: string,
/**
 * Gas used when the transaction is confirmed.
 */
gasUsed: bigint | null,
/**
 * Opaque decoded calldata descriptor.
 */
decodedCalldata: unknown | null,
/**
 * Optional memo extracted from the transaction.
 */
memo: string | null,
/**
 * DAG round associated with finality, when available.
 */
round: bigint | null,
/**
 * Cluster id associated with finality, when available.
 */
clusterId: number | null,
/**
 * Opaque BLS attestation payload.
 */
blsAttestation: unknown | null,
/**
 * PQ-finality attestation payload.
 */
pqAttestation: DecodeTxPqAttestation | null,
/**
 * Opaque finality proof payload.
 */
finalityProof: unknown | null,
/**
 * Logs emitted by the transaction.
 */
logs: Array<DecodeTxLog>,
/**
 * `success`, `reverted`, `unknown`, or a forward-compatible string.
 */
status: string,
/**
 * Node-supplied execution error code when available.
 */
errorCode: string | null, };
