// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecodeTxExtension } from "./DecodeTxExtension.js";
import type { DecodeTxLog } from "./DecodeTxLog.js";
import type { DecodeTxPqAttestation } from "./DecodeTxPqAttestation.js";
import type { NativeReceiptFee } from "./NativeReceiptFee.js";

/**
 * `lyth_decodeTx` response.
 */
export type DecodeTxResponse = {
/**
 * Transaction hash.
 */
txHash: string,
/**
 * Containing block hash.
 */
blockHash: string,
/**
 * Containing block number.
 */
blockNumber: bigint,
/**
 * Transaction index within the block.
 */
txIndex: number,
/**
 * Sender address.
 */
from: string,
/**
 * Recipient address, or `null` for contract creation.
 */
to: string | null,
/**
 * Transferred native value as a hex lythoshi quantity.
 */
value: string,
/**
 * Sender nonce.
 */
nonce: bigint,
/**
 * Execution-unit limit.
 */
executionUnitLimit: bigint,
/**
 * Max execution fee in lythoshi.
 */
maxExecutionFeeLythoshi: string,
/**
 * Priority tip in lythoshi.
 */
priorityTipLythoshi: string,
/**
 * Execution units used when the transaction is confirmed.
 */
executionUnitsUsed: bigint | null,
/**
 * Structured native fee summary.
 */
fee: NativeReceiptFee,
/**
 * Opaque decoded calldata descriptor.
 */
decodedCalldata: unknown | null,
/**
 * Optional memo extracted from the transaction.
 */
memo: string | null,
/**
 * Signed transaction extensions carried by the decoded transaction.
 */
extensions: Array<DecodeTxExtension>,
/**
 * DAG round associated with finality, when available.
 */
round: bigint | null,
/**
 * Cluster id associated with finality, when available.
 */
clusterId: number | null,
/**
 * Opaque round attestation payload.
 */
roundAttestation: unknown | null,
/**
 * PQ-finality attestation payload.
 */
pqAttestation: DecodeTxPqAttestation | null,
/**
 * Opaque finality proof payload.
 */
finalityProof: unknown | null,
/**
 * Logs emitted by the transaction.
 */
logs: Array<DecodeTxLog>,
/**
 * `success`, `reverted`, `unknown`, or a forward-compatible string.
 */
status: string,
/**
 * Node-supplied execution error code when available.
 */
errorCode: string | null, };
