// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PQ-finality attestation included in `lyth_decodeTx` when available.
 */
export type DecodeTxPqAttestation = {
/**
 * Checkpoint height that attests the transaction.
 */
checkpointHeight: bigint,
/**
 * Checkpointed state root.
 */
stateRoot: string,
/**
 * Signer id that produced the attestation.
 */
signerId: string,
/**
 * Scheme-prefixed signer signature.
 */
signature: string, };
