// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transaction extension descriptor included in `lyth_decodeTx`.
 */
export type DecodeTxExtension = {
/**
 * Extension kind byte as a number.
 */
kind: number,
/**
 * Extension kind byte as `0x`-hex.
 */
kindHex: string,
/**
 * Extension body bytes as `0x`-hex.
 */
bodyHex: string,
/**
 * Alias of `bodyHex` emitted by `mono-core` for explorer consumers.
 */
body: string, };
