// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Log row included in `lyth_decodeTx`.
 */
export type DecodeTxLog = {
/**
 * Contract address that emitted the log.
 */
address: string,
/**
 * Indexed topics.
 */
topics: Array<string>,
/**
 * ABI-encoded log data.
 */
data: string, };
