// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-wallet delegation event row surfaced by `lyth_getDelegationHistory`.
 */
export type DelegationHistoryRecord = {
/**
 * Block height the event landed in.
 */
blockHeight: bigint,
/**
 * Tx index within the block.
 */
txIndex: number,
/**
 * Log index within the tx.
 */
logIndex: number,
/**
 * Wallet that performed the delegation move.
 */
wallet: string,
/**
 * Source or only cluster id.
 */
cluster: number,
/**
 * Destination cluster id for redelegations.
 */
toCluster: number | null,
/**
 * Event kind: `delegated`, `undelegated`, or `redelegated`.
 */
kind: string,
/**
 * Weight moved in basis points.
 */
weightBps: number,
/**
 * Wallet total committed weight after the event when known.
 */
walletTotalBps: number | null,
};
