// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `lyth_getDelegationCap` response.
 */
export type DelegationCapResponse = {
/**
 * Per-cluster cap in basis points. `u32::MAX` means disabled.
 */
capBps: number,
/**
 * Height of the most recent milestone that changed the cap.
 */
lastChangedAtHeight: bigint,
/**
 * Block height sampled by the node.
 */
blockNumber: bigint, };
