// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One delegation row in `lyth_getDelegations`.
 */
export type DelegationRow = {
/**
 * Cluster id receiving the delegated weight.
 */
cluster: number,
/**
 * Delegated weight in basis points.
 */
weightBps: number, };
