// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DelegationRow } from "./DelegationRow.js";

/**
 * `lyth_getDelegations` response.
 */
export type DelegationsResponse = { 
/**
 * Queried wallet address.
 */
wallet: string, 
/**
 * Per-cluster delegation rows.
 */
rows: Array<DelegationRow>, 
/**
 * Sum of row weights.
 */
totalBps: number, 
/**
 * Block selector echoed by the node.
 */
block: unknown, };
