// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `lyth_getEncryptionKey` response.
 */
export type EncryptionKeyResponse = {
/**
 * KEM algorithm tag.
 */
algo: string,
/**
 * Cluster encryption epoch.
 */
epoch: bigint,
/**
 * ML-KEM-768 encapsulation key.
 */
encapsulationKey: string, };
