// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `lyth_getEntityRatchet` response.
 */
export type EntityRatchetResponse = {
/**
 * Active foundation-entity cluster count.
 */
active: number,
/**
 * Published ratchet threshold. `u32::MAX` means unset.
 */
threshold: number,
/**
 * Block selector echoed by the node.
 */
block: unknown, };
