// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `lyth_executionUnitPrice` response.
 */
export type ExecutionUnitPriceResponse = {
/**
 * Total execution-unit price in lythoshi.
 */
executionUnitPriceLythoshi: string,
/**
 * Base price component in lythoshi.
 */
basePricePerExecutionUnitLythoshi: string,
/**
 * Priority tip component in lythoshi.
 */
priorityTipLythoshi: string,
/**
 * Block height that produced the quote, or `null` for mempool-floor quotes.
 */
blockNumber: number | null,
/**
 * Quote source label returned by the node.
 */
source: string, };
