// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One retained ingestion/indexing gap.
 */
export type GapRecord = {
/**
 * First block in the gap.
 */
startBlock: bigint,
/**
 * Last block in the gap.
 */
endBlock: bigint,
/**
 * Number of blocks in the gap.
 */
blockCount: bigint,
/**
 * Start timestamp in UNIX seconds.
 */
startTimestamp: bigint,
/**
 * End timestamp in UNIX seconds.
 */
endTimestamp: bigint,
/**
 * Duration in seconds.
 */
durationSeconds: bigint,
/**
 * Node-supplied reason label.
 */
reason: string, };
