// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requested block range in `lyth_gapRecords`.
 */
export type GapRange = {
/**
 * First block in the requested range.
 */
fromBlock: bigint,
/**
 * Last block in the requested range.
 */
toBlock: bigint, };
