// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GapRange } from "./GapRange.js";
import type { GapRecord } from "./GapRecord.js";

/**
 * `lyth_gapRecords` response.
 */
export type GapRecordsResponse = {
/**
 * Response schema version.
 */
schemaVersion: number,
/**
 * Requested range.
 */
range: GapRange,
/**
 * Gap rows in the requested range.
 */
gapRecords: Array<GapRecord>, };
