// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregate gossip-mesh health bands in `lyth_peerSummary`.
 */
export type HealthSummary = { synced: bigint, lagging: bigint, stale: bigint, };
