// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `lyth_indexerStatus` envelope. `null` on the wire surfaces as
 * `Option::None` here.
 */
export type IndexerStatus = { 
/**
 * Highest block fully ingested.
 */
currentHeight: bigint, 
/**
 * Highest block observed.
 */
latestHeight?: bigint, 
/**
 * Active schema version.
 */
schemaVersion: number, };
