// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ping-RTT histogram bands in `lyth_peerSummary`.
 */
export type LatencyBands = { lt_50ms: bigint, lt_200ms: bigint, lt_1s: bigint, ge_1s: bigint, };
