// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProofRequestRow } from "./ProofRequestRow.js";

/**
 * `lyth_listProofRequests` response envelope.
 *
 * When the node runs without the prover-market indexer projection it
 * returns the graceful fallback `{ status: "indexer_unavailable", … }`
 * with an empty `requests` array — `requests` is always present so
 * callers can iterate unconditionally.
 */
export type ListProofRequestsResponse = {
/**
 * Response schema version (`1`).
 */
schemaVersion: number,
/**
 * `"indexer_unavailable"` on the graceful-fallback path; absent when served.
 */
status: string | null,
/**
 * Data source — `"prover_market_indexer_projection"`.
 */
source: string,
/**
 * Prover-market precompile address (`0x100C`).
 */
precompile: string,
/**
 * Echo of the lifecycle-state filter, when one was supplied.
 */
stateFilter: string | null,
/**
 * Echo of the page cap, when served.
 */
limit: number | null,
/**
 * Matching rows, newest-first. Empty on the fallback path.
 */
requests: Array<ProofRequestRow>,
/**
 * Human-readable reason on the fallback path.
 */
reason: string | null, };
