// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LythUpgradePlanStatus } from "./LythUpgradePlanStatus.js";

/**
 * `lyth_upgradeStatus` response.
 */
export type LythUpgradeStatusResponse = { chainId: bigint, blockNumber: bigint, configured: boolean, planCount: number, state: string, active: LythUpgradePlanStatus | null, pendingCount: number, pending: Array<LythUpgradePlanStatus>, };
