// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One signed upgrade plan in `lyth_upgradeStatus`.
 */
export type LythUpgradePlanStatus = { upgradeId: string, activationHeight: bigint, activationRound: bigint | null, requiredBinaryVersion: string, expectedBinaryDigest: string, p2pProtocolVersion: number, requiredFeatures: Array<string>, milestoneFileDigest: string | null, stateMigrationId: string | null, stateMigrationHash: string | null, expectedPreStateRoot: string | null, expectedPostStateRoot: string | null, };
