// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `lyth_mempoolStatus` aggregate.
 */
export type MempoolSnapshot = { 
/**
 * Tx count in the Ready bucket.
 */
count_ready: bigint, 
/**
 * Tx count in the Pending bucket.
 */
count_pending: bigint, 
/**
 * Mailbox depth gauge.
 */
mailbox_depth: bigint, 
/**
 * Bytes held per tx class.
 */
bytes_by_class: [bigint, bigint, bigint, bigint, bigint, bigint, bigint], };
