// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `mesh_buildUnsignedTx` response.
 */
export type MeshUnsignedTxResponse = {
/**
 * `0x`-hex bincode unsigned transaction envelope.
 */
unsigned_tx: string,
/**
 * `0x`-hex signing hash for the wallet.
 */
sighash: string, };
