// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `mesh_combineTx` response.
 */
export type MeshSignedTxResponse = {
/**
 * `0x`-hex bincode signed transaction envelope.
 */
signed_tx: string, };
