// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Intent accepted by `mesh_buildUnsignedTx`.
 */
export type MeshTxIntent = {
/**
 * Sender nonce, hex or decimal string.
 */
nonce: string,
/**
 * EIP-1559 max fee per gas, hex or decimal string.
 */
max_fee_per_gas: string,
/**
 * EIP-1559 max priority fee per gas, hex or decimal string.
 */
max_priority_fee_per_gas: string,
/**
 * Gas limit, hex or decimal string.
 */
gas_limit: string,
/**
 * Recipient address. `None` means contract creation.
 */
to?: string,
/**
 * Value, hex or decimal string.
 */
value?: string,
/**
 * Input/calldata hex.
 */
input?: string,
/**
 * Optional chain id override, hex or decimal string.
 */
chain_id?: string, };
