// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `mesh_decodeTx` response.
 */
export type MeshDecodedTx = {
/**
 * Chain id as a hex quantity.
 */
chain_id: string,
/**
 * Nonce as a hex quantity.
 */
nonce: string,
/**
 * Max priority fee per gas as a decimal string.
 */
max_priority_fee_per_gas: string,
/**
 * Max fee per gas as a decimal string.
 */
max_fee_per_gas: string,
/**
 * Gas limit as a JSON number.
 */
gas_limit: bigint,
/**
 * Recipient address, or null for contract creation.
 */
to: string | null,
/**
 * Value as a decimal string.
 */
value: string,
/**
 * Input/calldata hex.
 */
input: string,
/**
 * Present when decoding an unsigned transaction.
 */
sighash?: string,
/**
 * Present when decoding a signed transaction.
 */
from?: string,
/**
 * Present when decoding a signed transaction.
 */
tx_hash?: string, };
