// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricsRangeSeries } from "./MetricsRangeSeries.js";

/**
 * `lyth_metricsRange` response.
 */
export type MetricsRangeResponse = { schemaVersion: number, range: [bigint, bigint] | null, tracking: string, series: Array<MetricsRangeSeries>, };
