// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricsRangeSample } from "./MetricsRangeSample.js";

/**
 * One selector row in `lyth_metricsRange`.
 */
export type MetricsRangeSeries = { selector: string, status: string, unit: string | null, samples: Array<MetricsRangeSample> | null, };
