// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One retained metrics sample.
 */
export type MetricsRangeSample = { blockNumber: bigint, value: bigint, };
