// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MrcAccountRecord } from "./MrcAccountRecord.js";
import type { MrcPolicySpendRecord } from "./MrcPolicySpendRecord.js";

/**
 * `lyth_mrcAccount` exact current-state smart/policy account lookup response.
 */
export type MrcAccountResponse = {
/**
 * Response schema version.
 */
schemaVersion: number,
/**
 * Queried account address.
 */
account: string,
/**
 * Policy spend row limit applied by the node.
 */
spendLimit: number,
/**
 * Smart-account row, or `null` when none exists.
 */
smartAccount: MrcAccountRecord | null,
/**
 * Policy-account row, or `null` when none exists.
 */
policyAccount: MrcAccountRecord | null,
/**
 * Policy spend rows for this account.
 */
policySpends: Array<MrcPolicySpendRecord>, };
