// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current-state smart/policy account row folded from native MRC account events.
 */
export type MrcAccountRecord = {
/**
 * Account row kind: `smart_account` or `policy_account`.
 */
kind: string,
/**
 * Account address this row describes.
 */
account: string,
/**
 * Controller address authorized for this account.
 */
controller: string,
/**
 * Recovery address registered for this account, when smart-account state carries one.
 */
recovery: string | null,
/**
 * Active policy hash, when this row is a policy account.
 */
policyHash: string | null,
/**
 * Account nonce as decimal text, or `null` when the row has no nonce.
 */
nonce: string | null,
/**
 * Block height of the latest fold into this row.
 */
updatedAtBlock: number, };
