// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request parameters for `lyth_mrcAccount` and `/api/v1/mrc/accounts/{account}`.
 */
export type MrcAccountRequest = {
/**
 * Account address to inspect.
 */
account: string,
/**
 * Optional spend-row limit.
 */
spendLimit?: number, };
