// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MrcPolicyRecord } from "./MrcPolicyRecord.js";

/**
 * Current-state smart/policy account row folded from native MRC account events.
 */
export type MrcAccountRecord = {
/**
 * Account row kind: `smart_account` or `policy_account`.
 */
kind: string,
/**
 * Account address this row describes.
 */
account: string,
/**
 * Controller address authorized for this account.
 */
controller: string,
/**
 * Recovery address registered for this account, when smart-account state
 * carries one. ADVISORY / DISPLAY-ONLY: this is an inert stored field —
 * the chain has no on-chain account `Recover` / `RotateController` path
 * yet, so a registered recovery address cannot currently be exercised.
 * Surfaces MUST NOT present this as a working "recover account" action.
 */
recovery: string | null,
/**
 * Active policy hash, when this row is a policy account.
 */
policyHash: string | null,
/**
 * Active policy body, when this row is a policy account and the node has indexed it.
 */
policy: MrcPolicyRecord | null,
/**
 * Account nonce as decimal text, or `null` when the row has no nonce.
 */
nonce: string | null,
/**
 * Block height of the latest fold into this row.
 */
updatedAtBlock: number, };
