// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RichListHolder } from "./RichListHolder.js";

/**
 * `lyth_mrcHolders` response.
 */
export type MrcHoldersResponse = {
/**
 * Response schema version.
 */
schemaVersion: number,
/**
 * Queried MRC standard.
 */
standard: string,
/**
 * Queried MRC asset or collection id.
 */
assetId: string,
/**
 * Queried token id, or `null` for MRC-4626 vault scope.
 */
tokenId: string | null,
/**
 * Result limit applied by the node.
 */
limit: number,
/**
 * Holder rows. The row shape is shared with `lyth_richList`.
 */
holders: Array<RichListHolder>, };
