// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request parameters for `lyth_mrcHolders` and `/api/v1/mrc/.../holders`.
 */
export type MrcHoldersRequest = {
/**
 * MRC standard, for example `mrc20`, `mrc721`, or `mrc1155`.
 */
standard: string,
/**
 * MRC asset id, or collection id for token-specific standards.
 */
assetId: string,
/**
 * Token id inside the MRC holder namespace.
 */
tokenId: string,
/**
 * Optional result limit.
 */
limit?: number, };
