// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request parameters for `lyth_mrcHolders` and `/api/v1/mrc/.../holders`.
 */
export type MrcHoldersRequest = {
/**
 * MRC standard, for example `mrc20`, `mrc721`, `mrc1155`, or `mrc4626`.
 */
standard: string,
/**
 * MRC asset id, collection id, or MRC-4626 vault id.
 */
assetId: string,
/**
 * Token id inside the MRC holder namespace; `null`/omitted for MRC-4626 vault scope.
 */
tokenId?: string | null,
/**
 * Optional result limit.
 */
limit?: number, };
