// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MrcMetadataRecord } from "./MrcMetadataRecord.js";

/**
 * `lyth_mrcMetadata` exact current-state metadata lookup response.
 */
export type MrcMetadataResponse = {
/**
 * Response schema version.
 */
schemaVersion: number,
/**
 * Queried asset, collection, or vault id.
 */
assetId: string,
/**
 * Queried token id, or `null` for asset/collection scope.
 */
tokenId: string | null,
/**
 * Metadata row, or `null` when no aggregate exists for the key.
 */
metadata: MrcMetadataRecord | null, };
