// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current-state metadata folded from native MRC creation/metadata events.
 */
export type MrcMetadataRecord = {
/**
 * MRC standard: `mrc20`, `mrc721`, `mrc1155`, or `mrc4626`.
 */
standard: string,
/**
 * Asset, collection, or vault id.
 */
assetId: string,
/**
 * Token id for token-specific metadata rows.
 */
tokenId: string | null,
/**
 * Human-readable name, when carried by the source event.
 */
name: string | null,
/**
 * Short symbol, when carried by the source event.
 */
symbol: string | null,
/**
 * Display decimals, when carried by the source event.
 */
decimals: number | null,
/**
 * Metadata URI, when carried by the source event.
 */
uri: string | null,
/**
 * Block height of the latest fold into this row.
 */
updatedAtBlock: number, };
