// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Canonical MRC policy-account spending policy body.
 */
export type MrcPolicyRecord = {
/**
 * Whether the policy currently allows spending.
 */
enabled: boolean,
/**
 * Maximum amount per action as decimal text.
 */
perActionLimit: string,
/**
 * Maximum amount inside one window as decimal text.
 */
windowLimit: string,
/**
 * Assets allowed by this policy.
 */
allowedAssets: Array<string>, };
