// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current-state policy spend row included in `lyth_mrcAccount`.
 */
export type MrcPolicySpendRecord = {
/**
 * Policy account address.
 */
account: string,
/**
 * Asset id governed by this spend window.
 */
assetId: string,
/**
 * Spend window identifier as decimal text.
 */
window: string,
/**
 * Window allowance amount as decimal text.
 */
amount: string,
/**
 * Amount already spent in this window as decimal text.
 */
spent: string,
/**
 * Block height of the latest fold into this row.
 */
updatedAtBlock: number, };
