// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MrvAbiManifest } from "./MrvAbiManifest.js";
import type { MrvBuildMetadata } from "./MrvBuildMetadata.js";
import type { MrvMemoryLimits } from "./MrvMemoryLimits.js";
import type { MrvRiscvProfile } from "./MrvRiscvProfile.js";
import type { MrvStorageNamespace } from "./MrvStorageNamespace.js";
import type { MrvSyscallImport } from "./MrvSyscallImport.js";

/**
 * SDK JSON metadata for an MRV artifact.
 */
export type MrvArtifactMetadata = {
/**
 * MRV format version.
 */
formatVersion: number,
/**
 * Approved RISC-V profile.
 */
profile: MrvRiscvProfile,
/**
 * BLAKE3 hash of the code section.
 */
codeHash: string,
/**
 * Code byte count expected by this metadata.
 */
codeBytes: bigint,
/**
 * Optional debug byte count. Debug bytes are excluded from consensus hash.
 */
debugBytes: bigint,
/**
 * Contract ABI manifest.
 */
abi: MrvAbiManifest,
/**
 * Host syscall imports declared by the artifact.
 */
imports: Array<MrvSyscallImport>,
/**
 * Bounded memory declaration.
 */
memory: MrvMemoryLimits,
/**
 * Contract storage namespace.
 */
storageNamespace: MrvStorageNamespace,
/**
 * Build metadata.
 */
build: MrvBuildMetadata, };
