// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ABI symbol kind.
 */
export type MrvAbiSymbolKind = "constructor" | "function" | "event";
