// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ABI value type.
 */
export type MrvAbiType = { "kind": "unit" } | { "kind": "bool" } | { "kind": "u8" } | { "kind": "u32" } | { "kind": "u64" } | { "kind": "u128" } | { "kind": "bytes" } | { "kind": "fixedBytes",
/**
 * Fixed byte length.
 */
len: number, } | { "kind": "string" } | { "kind": "address" } | { "kind": "hash" };
