// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MrvAbiParam } from "./MrvAbiParam.js";
import type { MrvAbiSymbolKind } from "./MrvAbiSymbolKind.js";

/**
 * ABI symbol exposed by a contract.
 */
export type MrvAbiSymbol = {
/**
 * Stable symbol name.
 */
name: string,
/**
 * Symbol kind.
 */
kind: MrvAbiSymbolKind,
/**
 * Typed input parameters.
 */
inputs: Array<MrvAbiParam>,
/**
 * Typed output parameters.
 */
outputs: Array<MrvAbiParam>, };
