// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MrvAbiSymbol } from "./MrvAbiSymbol.js";

/**
 * Contract ABI manifest.
 */
export type MrvAbiManifest = {
/**
 * ABI symbols exposed by this artifact.
 */
symbols: Array<MrvAbiSymbol>, };
