// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MrvAbiType } from "./MrvAbiType.js";

/**
 * ABI parameter.
 */
export type MrvAbiParam = {
/**
 * Stable parameter name.
 */
name: string,
/**
 * Parameter type.
 */
ty: MrvAbiType, };
