// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Build metadata recorded in an MRV artifact.
 */
export type MrvBuildMetadata = {
/**
 * Toolchain identifier.
 */
toolchain: string,
/**
 * `0x`-prefixed source or build-input digest.
 */
sourceDigest: string,
/**
 * Reproducible build profile label.
 */
profile: string, };
