// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Native MRV contract call request model.
 */
export type MrvCallRequest = {
/**
 * Optional typed user address that signs the call.
 */
from?: string,
/**
 * Destination typed contract address (`monoc1...`).
 */
contractAddress: string,
/**
 * Call input bytes as `0x`-hex.
 */
input: string,
/**
 * Native value sent with the call, in lythoshi.
 */
valueLythoshi: string,
/**
 * Optional execution-unit ceiling for transaction admission.
 */
executionUnitLimit?: bigint,
/**
 * Optional max execution fee in lythoshi.
 */
maxExecutionFeeLythoshi?: string,
/**
 * Optional priority tip in lythoshi.
 */
priorityTipLythoshi?: string,
/**
 * Optional signer nonce.
 */
nonce?: bigint, };
