// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MrvCallStatus } from "./MrvCallStatus.js";
import type { MrvExecutionReceipt } from "./MrvExecutionReceipt.js";

/**
 * Native MRV call response model.
 */
export type MrvCallResponse = {
/**
 * Transaction hash.
 */
txHash: string,
/**
 * Execution status.
 */
status: MrvCallStatus,
/**
 * Returned bytes as `0x`-hex when available.
 */
returnData: string,
/**
 * Typed RISC-V receipt when available.
 */
receipt?: MrvExecutionReceipt, };
