// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Versioned MRV deploy payload envelope.
 *
 * Raw artifact deploys remain valid. This envelope is only needed when a
 * deploy carries optional constructor input alongside the canonical artifact.
 */
export type MrvDeployPayload = {
/**
 * Payload schema version.
 */
version: number,
/**
 * Canonical MRV artifact bytes.
 */
artifact: Array<number>,
/**
 * Optional constructor input already encoded with the artifact ABI.
 */
constructor: Array<number> | null, };
