// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Native MRV deploy request model.
 */
export type MrvDeployRequest = {
/**
 * Optional typed user address that signs the deploy.
 */
from?: string,
/**
 * Raw bincode MRV artifact bytes as `0x`-hex.
 */
artifactBytes: string,
/**
 * Native value to endow the contract with, in lythoshi.
 */
valueLythoshi: string,
/**
 * Optional execution-unit ceiling for transaction admission.
 */
executionUnitLimit?: bigint,
/**
 * Optional max execution fee in lythoshi.
 */
maxExecutionFeeLythoshi?: string,
/**
 * Optional priority tip in lythoshi.
 */
priorityTipLythoshi?: string,
/**
 * Optional signer nonce.
 */
nonce?: bigint, };
