// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MrvExecutionReceipt } from "./MrvExecutionReceipt.js";

/**
 * Native MRV deploy response model.
 */
export type MrvDeployResponse = {
/**
 * Transaction hash.
 */
txHash: string,
/**
 * Deployed typed contract address (`monoc1...`).
 */
contractAddress: string,
/**
 * Artifact hash when supplied by the node/indexer.
 */
artifactHash?: string,
/**
 * Receipt when the caller requested a confirmed response.
 */
receipt?: MrvExecutionReceipt, };
