// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed event payload emitted by a contract or native module.
 */
export type MrvEventRecord = {
/**
 * Domain-separated event topic as `0x`-hex.
 */
topic: string,
/**
 * Event payload bytes as `0x`-hex.
 */
data: string, };
