// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MrvEventRecord } from "./MrvEventRecord.js";
import type { MrvMeterCounters } from "./MrvMeterCounters.js";
import type { MrvNativeStateDelta } from "./MrvNativeStateDelta.js";
import type { MrvRevertPayload } from "./MrvRevertPayload.js";

/**
 * Typed RISC-V execution receipt.
 */
export type MrvExecutionReceipt = {
/**
 * Consensus hash of the validated MRV artifact as `0x`-hex.
 */
artifactHash: string,
/**
 * Execution counters.
 */
counters: MrvMeterCounters,
/**
 * Typed events emitted by the call.
 */
events: Array<MrvEventRecord>,
/**
 * Native module deltas produced by the call.
 */
nativeDeltas: Array<MrvNativeStateDelta>,
/**
 * Revert payload when execution failed through the typed revert path.
 */
reverted?: MrvRevertPayload, };
