// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Independent counters reported by MRV execution.
 */
export type MrvMeterCounters = {
/**
 * Deterministic instruction-cycle count.
 */
cycles: bigint,
/**
 * Units consumed by host syscalls.
 */
syscallUnits: bigint,
/**
 * Units consumed by authenticated state reads and writes.
 */
stateIoUnits: bigint, };
