// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bounded memory declaration for an MRV artifact.
 */
export type MrvMemoryLimits = {
/**
 * Initial memory pages available at contract start.
 */
initialPages: number,
/**
 * Maximum memory pages the contract may grow to.
 */
maxPages: number,
/**
 * Stack reservation in bytes.
 */
stackBytes: number, };
