// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MrvStorageNamespace } from "./MrvStorageNamespace.js";

/**
 * Typed native-module state delta for receipts and indexers.
 */
export type MrvNativeStateDelta = {
/**
 * Native module namespace that changed.
 */
namespace: MrvStorageNamespace,
/**
 * State key inside the namespace as `0x`-hex.
 */
key: string,
/**
 * Hash of the new value, or absent when the key was deleted.
 */
valueHash?: string, };
