// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed revert payload.
 */
export type MrvRevertPayload = {
/**
 * Stable contract-defined revert code.
 */
code: number,
/**
 * Opaque revert data as `0x`-hex.
 */
data: string, };
