// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Host syscall import declared by an artifact.
 */
export type MrvSyscallImport = {
/**
 * Host module name. Must be `mono`.
 */
module: string,
/**
 * Stable syscall import name.
 */
name: string,
/**
 * Stable numeric syscall identifier.
 */
id: number, };
