// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable storage namespace declaration.
 */
export type MrvStorageNamespace = {
/**
 * Lowercase namespace name.
 */
name: string,
/**
 * Namespace schema version.
 */
version: number, };
