// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed MRV transaction extension descriptor.
 */
export type MrvTransactionExtension = {
/**
 * Extension kind byte.
 */
kind: number,
/**
 * Extension body bytes as `0x`-hex.
 */
bodyHex: string, };
