// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MrvAddressKind } from "./MrvAddressKind.js";

/**
 * Decoded typed bech32m address.
 */
export type MrvTypedAddress = {
/**
 * ADR-0038 address kind.
 */
kind: MrvAddressKind,
/**
 * Typed bech32m address string.
 */
address: string, };
