// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MrvMemoryLimits } from "./MrvMemoryLimits.js";
import type { MrvResolvedSyscall } from "./MrvResolvedSyscall.js";
import type { MrvRiscvProfile } from "./MrvRiscvProfile.js";
import type { MrvStorageNamespace } from "./MrvStorageNamespace.js";

/**
 * Validated artifact metadata summary.
 */
export type MrvValidatedArtifactMetadata = {
/**
 * Verified code hash.
 */
codeHash: string,
/**
 * Approved profile.
 */
profile: MrvRiscvProfile,
/**
 * Bounded memory declaration.
 */
memory: MrvMemoryLimits,
/**
 * Contract storage namespace.
 */
storageNamespace: MrvStorageNamespace,
/**
 * Resolved syscall imports in declared order.
 */
syscalls: Array<MrvResolvedSyscall>,
/**
 * Number of ABI symbols.
 */
abiSymbolCount: bigint,
/**
 * Verified code byte count.
 */
codeBytes: bigint, };
