// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current-state native agent service-discovery row.
 */
export type NativeAgentServiceStateRecord = { serviceId: string, provider: string, categoryHash?: string | null, metadataHash?: string | null, active: boolean, updatedAtBlock: bigint, };
