// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Echoed optional predicates for a native agent state response.
 */
export type NativeAgentStateResponseFilters = { policyId: string | null, escrowId: string | null, account: string | null, includePolicySpends: boolean, };
