// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Source metadata attached to a native agent current-state response.
 */
export type NativeAgentStateSource = { indexerProvider: string, projection: string, };
