// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filter object passed to `lyth_nativeMarketState` and
 * `/api/v1/native-market-state`.
 */
export type NativeMarketStateFilter = {
/**
 * Optional exact spot market lookup.
 */
marketId: string | null,
/**
 * Optional exact spot order lookup.
 */
orderId: string | null,
/**
 * Optional exact NFT listing lookup.
 */
listingId: string | null,
/**
 * Optional exact collection royalty lookup.
 */
collectionId: string | null,
/**
 * Optional user account filter. Scopes spot orders by owner and NFT listings by seller.
 */
account: string | null,
/**
 * Include bounded spot orders for a requested market/order.
 */
includeSpotOrders: boolean | null,
/**
 * Maximum rows per list.
 */
limit: number | null, };
