// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Native agent reputation review row.
 */
export type NativeAgentReputationReviewStateRecord = { reviewId: string, reviewer: string, subject: string, categoryId: number, speedScore: number, qualityScore: number, communicationScore: number, accuracyScore: number, payloadHash?: string | null, updatedAtBlock: bigint, };
