// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current-state native agent consent row.
 */
export type NativeAgentConsentStateRecord = { consentId: string, subject: string, grantee: string, scopeHash?: string | null, expiresAt?: number | null, active: boolean, updatedAtBlock: bigint, };
