// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current-state native agent spending-policy aggregate.
 */
export type NativeAgentPolicyStateRecord = { policyId: string, owner: string, controller: string, assetId: string, enabled: boolean, perActionLimit: string, windowLimit: string, windowSecs: bigint, updatedAtBlock: bigint, };
