// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * MRV forwarder deployment row for a native module surfaced by `lyth_capabilities`.
 */
export type NativeModuleForwarderDescriptor = {
/**
 * Native module namespace this forwarder calls, for example `"market"`.
 */
module: string,
/**
 * Byte length of the encoded forwarder request.
 */
requestBytes: number,
/**
 * Typed MRV contract address hosting the forwarder.
 */
contractAddress: string,
/**
 * MRV artifact profile used by the deployed forwarder.
 */
artifactProfile: string,
/**
 * Deployment/readiness status reported by the node.
 */
status: string,
/**
 * Whether the deployment has been verified against the expected artifact.
 */
deploymentVerified: boolean, };
