// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current-state native spot market aggregate.
 */
export type NativeSpotMarketStateRecord = { marketId: string, owner: string, baseAssetId: string, quoteAssetId: string, tickSize: string, lotSize: string, minQuantity: string, minNotional: string, tradeCount: string, totalVolumeBase: string, lastPrice: string | null, lastBlockHeight: bigint | null, createdAtBlock: bigint, updatedAtBlock: bigint, };
