// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current-state native agent arbiter registry row.
 */
export type NativeAgentArbiterStateRecord = { arbiterId: string, arbiter: string, tier?: number | null, metadataHash?: string | null, updatedAtBlock: bigint, };
