// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Echoed optional predicates for a native market state response.
 */
export type NativeMarketStateResponseFilters = { marketId: string | null, orderId: string | null, listingId: string | null, collectionId: string | null, includeSpotOrders: boolean, };
