// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Structured native fee object attached to a RISC-V/native receipt.
 */
export type NativeReceiptFee = {
/**
 * Total fee in lythoshi.
 */
total_lythoshi: string,
/**
 * Total fee formatted as LYTH numeric text without the unit suffix.
 */
total_lyth: string,
/**
 * Execution cycles charged by the receipt.
 */
cycles_used: bigint,
/**
 * Base price per execution cycle in lythoshi.
 */
base_price_per_cycle_lythoshi: string,
/**
 * Authenticated state I/O units charged by the receipt.
 */
state_io_units: bigint,
/**
 * State I/O unit price in lythoshi.
 */
state_io_price_per_unit_lythoshi: string,
/**
 * Priority tip in lythoshi.
 */
priority_tip_lythoshi: string, };
