// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current-state native agent provider availability row.
 */
export type NativeAgentAvailabilityStateRecord = { provider: string, maxConcurrent: number, openRequests: number, paused: boolean, updatedAtBlock: bigint, };
