// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current-state native agent arbiter registry row.
 */
export type NativeAgentArbiterStateRecord = { arbiterId: string, arbiter: string,
/**
 * Arbiter-local registration nonce captured by the native agent module.
 */
nonce?: number | null, tier?: number | null, metadataHash?: string | null, updatedAtBlock: bigint, };
