// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current-state native agent escrow aggregate.
 */
export type NativeAgentEscrowStateRecord = { escrowId: string, buyer: string, provider: string, arbiter: string, assetId: string, amount: string, termsHash: string, round: number, buyerAccepted: boolean, providerAccepted: boolean, submittedPayloadHash?: string | null, status: string, resolution?: string | null, lastActor?: string | null, createdAtBlock: bigint, updatedAtBlock: bigint, };
