// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filter object passed to `lyth_nativeAgentState` and
 * `/api/v1/native-agent-state`.
 */
export type NativeAgentStateFilter = {
/**
 * Optional exact spending-policy lookup.
 */
policyId: string | null,
/**
 * Optional exact escrow lookup.
 */
escrowId: string | null,
/**
 * Optional account scope for owner/controller/buyer/provider/arbiter rows.
 */
account: string | null,
/**
 * Include bounded policy spend rows for policy/account lookups.
 */
includePolicySpends: boolean | null,
/**
 * Maximum rows per list.
 */
limit: number | null, };
