// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current-state native spot order aggregate.
 */
export type NativeSpotOrderStateRecord = { orderId: string, marketId: string, owner: string,
/**
 * Owner-local spot order nonce captured from `LimitOrderPlaced`.
 */
nonce?: number | null, side: string, price: string, quantity: string, remaining: string, status: string, expiresAtBlock: bigint, updatedAtBlock: bigint, };
