// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current-state native agent policy spend usage row.
 */
export type NativeAgentPolicySpendStateRecord = { policyId: string, controller: string, assetId: string, window: bigint, amount: string, spent: string, updatedAtBlock: bigint, };
