// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current-state native agent attestation row.
 */
export type NativeAgentAttestationStateRecord = { attestationId: string,
/**
 * Issuer-local nonce captured when the attestation was issued.
 */
nonce?: number | null, issuerId?: string | null, issuer?: string | null, subject: string, schemaHash?: string | null, payloadHash?: string | null, active: boolean, updatedAtBlock: bigint, };
