// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current-state native agent issuer registry row.
 */
export type NativeAgentIssuerStateRecord = { issuerId: string, issuer: string, metadataHash?: string | null, updatedAtBlock: bigint, };
