// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current-state native agent issuer registry row.
 */
export type NativeAgentIssuerStateRecord = { issuerId: string, issuer: string,
/**
 * Issuer-local nonce captured by the native agent module.
 */
nonce?: number | null, metadataHash?: string | null, updatedAtBlock: bigint, };
