// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current-state collection royalty aggregate.
 */
export type NativeCollectionRoyaltyStateRecord = { collectionId: string, creator: string | null, recipient: string, bps: number, updatedAtBlock: bigint, };
