// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current-state native NFT listing aggregate.
 */
export type NativeNftListingStateRecord = { listingId: string, seller: string, standard: string, collectionId: string, tokenId: string, quantity: string, paymentAssetId: string, price: string, listingKind: unknown, status: string, expiresAtBlock: bigint, highestBidder: string | null, highestBid: string | null, updatedAtBlock: bigint, };
