// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NativeCollectionRoyaltyStateRecord } from "./NativeCollectionRoyaltyStateRecord.js";
import type { NativeMarketStateResponseFilters } from "./NativeMarketStateResponseFilters.js";
import type { NativeMarketStateSource } from "./NativeMarketStateSource.js";
import type { NativeNftListingStateRecord } from "./NativeNftListingStateRecord.js";
import type { NativeSpotMarketStateRecord } from "./NativeSpotMarketStateRecord.js";
import type { NativeSpotOrderStateRecord } from "./NativeSpotOrderStateRecord.js";

/**
 * Typed response returned by `lyth_nativeMarketState` and
 * `/api/v1/native-market-state`.
 */
export type NativeMarketStateResponse = { schemaVersion: number, limit: number, filters: NativeMarketStateResponseFilters, spotMarkets: Array<NativeSpotMarketStateRecord>, spotOrders: Array<NativeSpotOrderStateRecord>, nftListings: Array<NativeNftListingStateRecord>, collectionRoyalties: Array<NativeCollectionRoyaltyStateRecord>, source: NativeMarketStateSource, };
