// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NativeAgentArbiterStateRecord } from "./NativeAgentArbiterStateRecord.js";
import type { NativeAgentAttestationStateRecord } from "./NativeAgentAttestationStateRecord.js";
import type { NativeAgentAvailabilityStateRecord } from "./NativeAgentAvailabilityStateRecord.js";
import type { NativeAgentConsentStateRecord } from "./NativeAgentConsentStateRecord.js";
import type { NativeAgentEscrowStateRecord } from "./NativeAgentEscrowStateRecord.js";
import type { NativeAgentIssuerStateRecord } from "./NativeAgentIssuerStateRecord.js";
import type { NativeAgentPolicySpendStateRecord } from "./NativeAgentPolicySpendStateRecord.js";
import type { NativeAgentPolicyStateRecord } from "./NativeAgentPolicyStateRecord.js";
import type { NativeAgentReputationReviewStateRecord } from "./NativeAgentReputationReviewStateRecord.js";
import type { NativeAgentServiceStateRecord } from "./NativeAgentServiceStateRecord.js";
import type { NativeAgentStateResponseFilters } from "./NativeAgentStateResponseFilters.js";
import type { NativeAgentStateSource } from "./NativeAgentStateSource.js";

/**
 * Typed response returned by `lyth_nativeAgentState` and
 * `/api/v1/native-agent-state`.
 */
export type NativeAgentStateResponse = { schemaVersion: number, limit: number, filters: NativeAgentStateResponseFilters, issuers: Array<NativeAgentIssuerStateRecord>, attestations: Array<NativeAgentAttestationStateRecord>, consents: Array<NativeAgentConsentStateRecord>, services: Array<NativeAgentServiceStateRecord>, availability: Array<NativeAgentAvailabilityStateRecord>, arbiters: Array<NativeAgentArbiterStateRecord>, reputationReviews: Array<NativeAgentReputationReviewStateRecord>, spendingPolicies: Array<NativeAgentPolicyStateRecord>, policySpends: Array<NativeAgentPolicySpendStateRecord>, escrows: Array<NativeAgentEscrowStateRecord>, source: NativeAgentStateSource, };
