// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NativeAgentEscrowStateRecord } from "./NativeAgentEscrowStateRecord.js";
import type { NativeAgentPolicySpendStateRecord } from "./NativeAgentPolicySpendStateRecord.js";
import type { NativeAgentPolicyStateRecord } from "./NativeAgentPolicyStateRecord.js";
import type { NativeAgentStateResponseFilters } from "./NativeAgentStateResponseFilters.js";
import type { NativeAgentStateSource } from "./NativeAgentStateSource.js";

/**
 * Typed response returned by `lyth_nativeAgentState` and
 * `/api/v1/native-agent-state`.
 */
export type NativeAgentStateResponse = { schemaVersion: number, limit: number, filters: NativeAgentStateResponseFilters, spendingPolicies: Array<NativeAgentPolicyStateRecord>, policySpends: Array<NativeAgentPolicySpendStateRecord>, escrows: Array<NativeAgentEscrowStateRecord>, source: NativeAgentStateSource, };
