// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Hosting class an operator runs under (PF-6).
 *
 * Mirrors `node-registry::registration::HostingClass`. Decoded from
 * the right-aligned `u8` enum byte; any value outside `0..=2` falls
 * back to `Cloud` (the least-diverse class) so an unparseable byte
 * never inflates a cluster's diversity score.
 */
export type NodeHostingClass = "bareMetal" | "coLocation" | "cloud";
