// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeHostingClass } from "./NodeHostingClass.js";

/**
 * `getOperatorNetworkMetadata` view (PF-6).
 *
 * Mirrors the `(uint16 asn, bytes3 geoRegion, uint8 hostingClass,
 * bytes32 ipAddressHash, bytes32 pcrDigest)` return tuple. The raw IP
 * never lives on-chain — `ip_address_hash` is `keccak256(ipHint)`.
 * All fields are zero/`Cloud`/`0x00..0` if the peer never declared
 * metadata.
 */
export type OperatorNetworkMetadata = {
/**
 * Autonomous-system number; `0` = not declared.
 */
asn: number,
/**
 * ISO-3166-1 alpha-3 region as `0x`-prefixed 3-byte hex; all-zero
 * = not declared.
 */
geoRegion: string,
/**
 * Declared hosting class.
 */
hostingClass: NodeHostingClass,
/**
 * `keccak256` of the operator's public IP; `0x00..0` = not declared.
 */
ipAddressHash: string,
/**
 * `keccak256` of the TPM PCR digest; `0x00..0` = no quote attached.
 */
pcrDigest: string, };
