// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperatorSurfaceCapability } from "./OperatorSurfaceCapability.js";

/**
 * `lyth_operatorCapabilities` response.
 */
export type OperatorCapabilitiesResponse = { schemaVersion: number, surfaces: { [key in string]?: OperatorSurfaceCapability }, };
