// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `lyth_operatorFeeConfig` response — one operator's fee registration.
 *
 * Mirrors the chain JSON exactly (camelCase). A zero recipient is the
 * "operator not registered" sentinel on-chain, so the chain returns a
 * not-found error rather than this shape in that case.
 */
export type OperatorFeeConfig = {
/**
 * Response schema version (`1`).
 */
schemaVersion: number,
/**
 * Data source — `"native_state_storage"`.
 */
source: string,
/**
 * Router precompile address (`0x100B`).
 */
precompile: string,
/**
 * Operator the registration belongs to (`mono` bech32m).
 */
operator: string,
/**
 * Configured fee recipient (`mono` bech32m).
 */
recipient: string,
/**
 * Operator surcharge in basis points.
 */
feeBps: number,
/**
 * `true` when the operator's surcharge is active.
 */
enabled: boolean,
/**
 * Block height the operator was first registered at.
 */
registeredAtBlock: bigint, };
