// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Decoded `OperatorFeeCharged` log (`0x100B`).
 *
 * Mirrors `operator-router/src/events.rs::emit_operator_fee_charged_to_host`:
 * indexed `operator` / `user` / `market_id`; body `recipient`,
 * `quote_token`, `fee_amount`, `clob_order_id`. `clob_order_id` joins the
 * router fee to the CLOB `OrderPlaced` / `OrderMatched` rows.
 */
export type OperatorFeeChargedEvent = {
/**
 * Operator that charged the fee (`0x` 20-byte hex).
 */
operator: string,
/**
 * User that paid the fee (`0x` 20-byte hex).
 */
user: string,
/**
 * CLOB market id the order targets (`0x` 32 bytes).
 */
marketId: string,
/**
 * Fee recipient configured by the operator (`0x` 20-byte hex).
 */
recipient: string,
/**
 * Quote token the fee was skimmed in (`0x` 32 bytes).
 */
quoteToken: string,
/**
 * Fee amount skimmed (quote-token atoms, decimal string).
 */
feeAmount: string,
/**
 * CLOB order id the routed placement produced (`0x` 32 bytes).
 */
clobOrderId: string, };
