// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `lyth_operatorRouterConfig` response — the router's static posture.
 *
 * Mirrors the chain JSON exactly (camelCase). `enabled` reflects whether
 * the gateable router precompile is currently milestone-activated; the
 * read surfaces work regardless.
 */
export type OperatorRouterConfig = {
/**
 * Response schema version (`1`).
 */
schemaVersion: number,
/**
 * Data source — `"native_state_storage"`.
 */
source: string,
/**
 * Router precompile address (`0x100B`).
 */
routerAddress: string,
/**
 * On-chain protocol fee ceiling in bps (`100` = 1.00%).
 */
protocolMaxOperatorFeeBps: number,
/**
 * `true` when the router precompile is milestone-activated.
 */
enabled: boolean, };
