// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed view of one oracle-precompile log (MB-6).
 *
 * One variant per chain-side emit helper. `feed_id`, `evidence_hash`,
 * and address fields are `0x`-prefixed hex; `computed_median` / `value`
 * are decimal strings of their on-chain `uint256` value.
 */
export type OracleEvent = { "kind": "roundFinalized",
/**
 * Feed the round belongs to (`0x` 32 bytes).
 */
feedId: string,
/**
 * Round identifier.
 */
roundId: string,
/**
 * Computed median price (decimal string).
 */
computedMedian: string,
/**
 * Block at which the round finalized.
 */
finalizedAtBlock: string,
/**
 * Number of observations contributing to the median.
 */
observationsLen: number, } | { "kind": "observationSubmitted",
/**
 * Feed the observation targets (`0x` 32 bytes).
 */
feedId: string,
/**
 * Round the observation contributes to.
 */
roundId: string,
/**
 * Writer that submitted the observation (`0x` address).
 */
writer: string,
/**
 * Reported price (decimal string).
 */
value: string,
/**
 * Writer-observed timestamp.
 */
observedAt: string, } | { "kind": "fraudSlashed",
/**
 * Feed the slashed writer operated on (`0x` 32 bytes).
 */
feedId: string,
/**
 * Round the fraud proof targeted.
 */
roundId: string,
/**
 * Slashed writer (`0x` address).
 */
writer: string,
/**
 * Evidence hash carried in the slash record (`0x` 32 bytes).
 */
evidenceHash: string, } | { "kind": "feedAdded",
/**
 * Feed id (`0x` 32 bytes).
 */
feedId: string,
/**
 * Price decimals.
 */
decimals: number,
/**
 * Minimum signers to close a round.
 */
minSigners: number,
/**
 * Circuit-breaker bound in basis points.
 */
circuitBreakerBps: number,
/**
 * Number of allowed writers at registration.
 */
allowedWritersLen: number, } | { "kind": "feedUpdated",
/**
 * Feed id (`0x` 32 bytes).
 */
feedId: string,
/**
 * Price decimals.
 */
decimals: number,
/**
 * Minimum signers to close a round.
 */
minSigners: number,
/**
 * Circuit-breaker bound in basis points.
 */
circuitBreakerBps: number,
/**
 * Number of allowed writers after the update.
 */
allowedWritersLen: number, } | { "kind": "adminUpdated",
/**
 * New oracle admin (`0x` address).
 */
admin: string, } | { "kind": "writerAdded",
/**
 * Admin that authorized the addition (`0x` address).
 */
admin: string,
/**
 * Writer that was added (`0x` address).
 */
writer: string, } | { "kind": "writerRemoved",
/**
 * Admin that authorized the removal (`0x` address).
 */
admin: string,
/**
 * Writer that was removed (`0x` address).
 */
writer: string, };
