// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthSummary } from "./HealthSummary.js";
import type { LatencyBands } from "./LatencyBands.js";

/**
 * Public-safe aggregate returned by `lyth_peerSummary`.
 */
export type PeerSummaryAggregate = { peerCount: bigint, inboundCount: bigint | null, outboundCount: bigint | null, latencyBands: LatencyBands | null, versionDistribution: { [key in string]?: bigint }, healthSummary: HealthSummary, asOfBlock: bigint, };
