// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `debug_p2pPeers` entry.
 */
export type PeerSummary = { 
/**
 * libp2p peer id (base58).
 */
peerId: string, 
/**
 * Declared role.
 */
role: string, 
/**
 * Listen addresses.
 */
listenAddrs: Array<string>, 
/**
 * `agent_version` from libp2p identify.
 */
agentVersion: string, 
/**
 * Reputation score.
 */
score: number, 
/**
 * Whether the peer is in any gossip mesh.
 */
inMesh: boolean, };
