// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in `lyth_pendingRewards`.
 */
export type PendingRewardsRow = {
/**
 * Cluster id receiving the delegated weight.
 */
cluster: number,
/**
 * Delegated weight in basis points.
 */
weightBps: number,
/**
 * Unsettled reward-index delta for this cluster, as a hex quantity.
 */
unsettledAmountLythoshi: string, };
