// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PendingRewardsRow } from "./PendingRewardsRow.js";

/**
 * `lyth_pendingRewards` response.
 */
export type PendingRewardsResponse = {
/**
 * Queried wallet address.
 */
wallet: string,
/**
 * Settled plus unsettled claimable rewards, as a hex quantity.
 */
totalAmountLythoshi: string,
/**
 * Wallet-level pending reward already settled in storage.
 */
settledPendingLythoshi: string,
/**
 * Sum of per-cluster unsettled reward-index deltas.
 */
unsettledAmountLythoshi: string,
/**
 * Whether this wallet has auto-compounding enabled.
 */
autoCompound: boolean,
/**
 * Per-cluster unsettled rows.
 */
rows: Array<PendingRewardsRow>,
/**
 * Block selector echoed by the node.
 */
block: unknown, };
