// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `lyth_mempoolPending` per-tx entry.
 */
export type PendingTxSummary = {
/**
 * Tx hash.
 */
txHash: string,
/**
 * Sender nonce of this transaction.
 */
nonce: bigint,
/**
 * Class index (0..=6).
 */
class: number,
/**
 * Wire size in bytes.
 */
wireBytesLen: number,
/**
 * `true` if parked in the ready bucket.
 */
ready: boolean, };
