// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `lyth_listActivePrecompiles` entry — OI-0170 / ADR-0015 §5.
 */
export type PrecompileDescriptor = {
/**
 * 20-byte precompile address, `0x`-hex.
 */
address: string,
/**
 * Stable identifier (e.g. `"agent"`, `"oracle"`, `"delegation"`).
 */
name: string,
/**
 * Whether milestone gates can toggle this precompile.
 */
gateable: boolean,
/**
 * Whether the precompile is currently dispatchable.
 */
enabled: boolean,
/**
 * Stable capability id from the milestone registry.
 */
capabilityId: string,
/**
 * Height of the milestone that activated this capability, when any.
 */
activationHeight: bigint | null, };
