// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `lyth_listActivePrecompiles` entry — OI-0170 / ADR-0015 §5.
 */
export type PrecompileDescriptor = { 
/**
 * 20-byte precompile address, `0x`-hex.
 */
address: string, 
/**
 * Stable identifier (e.g. `"agent"`, `"oracle"`, `"delegation"`).
 */
name: string, 
/**
 * Whether the precompile is currently dispatchable.
 */
active: boolean, 
/**
 * Human-readable status string from the milestone gate registry.
 */
status: string, };
