// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `lyth_listProofRequests` row — one indexer-projection proof-request
 * record. Distinct from [`ProofRequestView`]: fee amounts here are
 * decimal atomic-unit strings (the indexer projection's wire form), and
 * the row carries `fee_paid` + `created_at_block` instead of the
 * state-tree-only `inputs_hash` / `state_code` / `proof_hash` fields.
 */
export type ProofRequestRow = {
/**
 * Content-addressed request id (`0x` 32 bytes).
 */
requestId: string,
/**
 * Requesting buyer (`mono` bech32m).
 */
buyer: string,
/**
 * Verification-key hash bound to the request (`0x` 32 bytes).
 */
vkeyHash: string,
/**
 * Maximum fee escrowed (decimal atomic-unit string).
 */
maxFee: string,
/**
 * Deadline (unix seconds).
 */
deadlineUnixSeconds: bigint,
/**
 * Lifecycle state name.
 */
state: string,
/**
 * Assigned prover (`mono` bech32m); `None` until a winner is selected.
 */
assignedProver: string | null,
/**
 * Winning fee (decimal atomic-unit string); `None` until assigned.
 */
winningFee: string | null,
/**
 * Number of bids recorded against the request.
 */
bidCount: number,
/**
 * Fee paid out on settlement (decimal atomic-unit string); `None` otherwise.
 */
feePaid: string | null,
/**
 * Block height the request was first observed at.
 */
createdAtBlock: bigint, };
