// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProverMarketState } from "./ProverMarketState.js";

/**
 * `lyth_getProofRequest` view of one [`ProofRequest`] record.
 *
 * `max_fee` / `winning_fee` are decimal strings; hashes + addresses
 * are `0x`-prefixed hex.
 */
export type ProofRequestView = {
/**
 * Canonical request id (`0x` 32 bytes).
 */
id: string,
/**
 * Buyer address (`0x` 20 bytes).
 */
buyer: string,
/**
 * Verification-key hash the proof must satisfy (`0x` 32 bytes).
 */
vkeyHash: string,
/**
 * Public-inputs commitment (`0x` 32 bytes).
 */
inputsHash: string,
/**
 * Maximum fee escrowed (lythoshi decimal string).
 */
maxFee: string,
/**
 * Deterministic Unix-seconds deadline.
 */
deadline: string,
/**
 * Buyer-supplied uniqueness nonce.
 */
nonce: string,
/**
 * Current state-machine state.
 */
state: ProverMarketState,
/**
 * Assigned prover (`0x` 20 bytes); zero-address while Open/Expired.
 */
assignedProver: string,
/**
 * Winning fee bid (lythoshi decimal string); `"0"` while Open.
 */
winningFee: string,
/**
 * Delivered proof hash (`0x` 32 bytes); zero until `submitProof`.
 */
proofHash: string, };
