// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `lyth_getProofRequest` response — one proof-request record read
 * directly from the prover-market state tree (`0x100C`).
 *
 * Mirrors the chain JSON exactly (camelCase keys). Fee amounts are
 * `0x`-hex `uint256` strings; addresses are `mono` bech32m (`None` when
 * unset); hashes are `0x`-hex words. This is the exact-lookup shape; the
 * indexer-backed list rows ([`ProofRequestRow`]) carry a different field
 * set.
 */
export type ProofRequestView = {
/**
 * Response schema version (`1`).
 */
schemaVersion: number,
/**
 * Data source — `"native_state_storage"`.
 */
source: string,
/**
 * Prover-market precompile address (`0x100C`).
 */
precompile: string,
/**
 * Canonical request id (`0x` 32 bytes).
 */
requestId: string,
/**
 * Lifecycle state name.
 */
state: string,
/**
 * Lifecycle state wire byte (`0`..=`4`).
 */
stateCode: number,
/**
 * Buyer (`mono` bech32m); `None` when unset.
 */
buyer: string | null,
/**
 * Verification-key hash the proof must satisfy (`0x` 32 bytes).
 */
vkeyHash: string,
/**
 * Public-inputs commitment (`0x` 32 bytes).
 */
inputsHash: string,
/**
 * Maximum fee escrowed (`0x`-hex `uint256`).
 */
maxFee: string,
/**
 * Deterministic Unix-seconds deadline.
 */
deadlineUnixSeconds: bigint,
/**
 * Assigned prover (`mono` bech32m); `None` while Open/Expired.
 */
assignedProver: string | null,
/**
 * Winning fee bid (`0x`-hex `uint256`); `0x0` while Open.
 */
winningFee: string,
/**
 * Unix seconds of the last state transition.
 */
stateAtUnixSeconds: bigint,
/**
 * Delivered proof hash (`0x` 32 bytes); zero until `submitProof`.
 */
proofHash: string,
/**
 * Number of bids recorded against the request.
 */
bidCount: number, };
