// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * State machine for a proof request (mirrors
 * `prover-market::core::ProverMarketState`).
 */
export type ProverMarketState = "open" | "assigned" | "settled" | "slashed" | "expired";
