// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProverBidView } from "./ProverBidView.js";

/**
 * `lyth_getProverBids` response — every recorded bid against one
 * request, read from the prover-market bid slots (`0x100C`).
 */
export type ProverBidsResponse = {
/**
 * Response schema version (`1`).
 */
schemaVersion: number,
/**
 * Data source — `"native_state_storage"`.
 */
source: string,
/**
 * Prover-market precompile address (`0x100C`).
 */
precompile: string,
/**
 * Request the bids target (`0x` 32 bytes).
 */
requestId: string,
/**
 * Number of bids recorded.
 */
bidCount: number,
/**
 * Recorded fee bids.
 */
bids: Array<ProverBidView>, };
