// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `lyth_getProverBids` view of one prover fee bid.
 */
export type ProverBidView = {
/**
 * Request this bid targets (`0x` 32 bytes).
 */
requestId: string,
/**
 * Bidding prover (`0x` 20 bytes); must hold `SERVES_GPU_PROVE`.
 */
prover: string,
/**
 * Fee bid (lythoshi decimal string); must be `<= max_fee`.
 */
fee: string, };
