// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One prover fee bid in a [`ProverBidsResponse`].
 */
export type ProverBidView = {
/**
 * Slot index of this bid within the request's bid list.
 */
index: number,
/**
 * Bidding prover (`mono` bech32m); must hold `SERVES_GPU_PROVE`.
 */
prover: string,
/**
 * Fee bid (`0x`-hex `uint256`); must be `<= max_fee`.
 */
fee: string, };
