// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `lyth_proverMarketStatus` response — market-wide prover-market stats.
 *
 * `fee_floor` is the on-chain genesis singleton (always present, read
 * directly from `0x100C`). The aggregate counts come from the indexer
 * projection; when the node runs without it the response carries
 * `status: "indexer_unavailable"` and the count fields are `None`.
 */
export type ProverMarketStatusResponse = {
/**
 * Response schema version (`1`).
 */
schemaVersion: number,
/**
 * `"indexer_unavailable"` on the graceful-fallback path; absent when served.
 */
status: string | null,
/**
 * Data source — `"prover_market_indexer_projection"`.
 */
source: string,
/**
 * Prover-market precompile address (`0x100C`).
 */
precompile: string,
/**
 * Genesis-configured minimum prover fee (`0x`-hex `uint256`).
 */
feeFloor: string,
/**
 * Requests in the `open` state; `None` on the fallback path.
 */
openRequests: bigint | null,
/**
 * Requests in the `assigned` state; `None` on the fallback path.
 */
assignedRequests: bigint | null,
/**
 * Requests in the `settled` state; `None` on the fallback path.
 */
settledRequests: bigint | null,
/**
 * Requests in the `slashed` state; absent on the fallback path.
 */
slashedRequests: bigint | null,
/**
 * Requests in the `expired` state; absent on the fallback path.
 */
expiredRequests: bigint | null,
/**
 * Total requests observed; absent on the fallback path.
 */
totalRequests: bigint | null,
/**
 * Human-readable reason on the fallback path.
 */
reason: string | null, };
