// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RedemptionQueueTicket } from "./RedemptionQueueTicket.js";

/**
 * `lyth_redemptionQueue` response.
 */
export type RedemptionQueueResponse = {
/**
 * Queried wallet address.
 */
wallet: string,
/**
 * Bounded wallet redemption tickets returned by the node.
 */
tickets: Array<RedemptionQueueTicket>,
/**
 * Total ticket count stored for the wallet.
 */
count: bigint,
/**
 * Number of decoded tickets returned.
 */
returned: number,
/**
 * Block selector echoed by the node.
 */
block: unknown, };
