// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One ticket in `lyth_redemptionQueue`.
 */
export type RedemptionQueueTicket = {
/**
 * Stable queue index for this wallet.
 */
index: bigint,
/**
 * Cluster id whose delegation weight is redeeming.
 */
cluster: number,
/**
 * Redeeming delegation weight in basis points.
 */
weightBps: number,
/**
 * Block height where the ticket was queued.
 */
createdHeight: bigint,
/**
 * Block height where the cooldown matures.
 */
maturityHeight: bigint,
/**
 * Whether the ticket is mature at the queried block, or `null`
 * when the selector does not resolve to a height.
 */
mature: boolean | null, };
