// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `lyth_listProviders` / `lyth_getRegistration` record.
 */
export type RegistryRecord = {
/**
 * libp2p peer id, `0x`-hex 32-byte.
 */
peerId: string,
/**
 * Capability bitmask.
 */
capabilities: number,
/**
 * Primary external endpoint URL.
 */
endpoint: string,
/**
 * Current bond, hex quantity.
 */
bond: string,
/**
 * Uptime in basis points (0..=10_000).
 */
uptimeBps: number,
/**
 * Block height the operator first registered at (operator "active
 * since"). Always present on the live `lyth_getRegistration` /
 * `lyth_listProviders` JSON.
 */
registeredAtBlock: bigint, };
