// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One holder row in `lyth_richList`.
 */
export type RichListHolder = {
/**
 * One-based holder rank.
 */
rank: number,
/**
 * Holder address.
 */
address: string,
/**
 * Balance as a decimal string.
 */
balance: string,
/**
 * Block height the balance was last observed at.
 */
updatedAtBlock: bigint, };
