// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RichListHolder } from "./RichListHolder.js";

/**
 * `lyth_richList` response.
 */
export type RichListResponse = {
/**
 * Response schema version.
 */
schemaVersion: number,
/**
 * Queried token id.
 */
tokenId: string,
/**
 * Result limit applied by the node.
 */
limit: number,
/**
 * Holder rows.
 */
holders: Array<RichListHolder>, };
