// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Round-advancement certificate response used by the AUD-0074
 * certificate RPCs (`lyth_getRoundCertificate` /
 * `lyth_getLeaderCertificate` / `lyth_getDacCertificate`).
 *
 * On the post-quantum chain the `signature` field is the ML-DSA-65
 * leader-seed digest — the BLAKE3 hash over the ML-DSA quorum
 * certificate that seeds the historical leader beacon. It is also the
 * value the VRF precompile (`0x1101`) reads as the historical
 * randomness for a finalized round.
 */
export type RoundCertificateResponse = {
/**
 * Round at which the certificate sealed.
 */
round: bigint,
/**
 * `0x`-prefixed leader-seed digest (ML-DSA-65 quorum-cert hash).
 * The JSON wire field stays `signature` for compatibility.
 */
signature: string,
/**
 * Signer-set bitmap as `0x`-hex bytes.
 */
signers_bitmap: string,
/**
 * Operator indices decoded from the signer bitmap.
 */
signer_indices: Array<number>,
/**
 * Number of signing operators.
 */
signer_count: number, };
