// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `lyth_currentRound` round shape.
 */
export type RoundInfo = { 
/**
 * Latest committed height.
 */
height: bigint, };
