// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One runtime-feature gate from the `lyth_capabilities` `runtimeFeatures`
 * map. Runtime features are milestone-folded execution dials that are **not**
 * bound to a precompile address (unlike [`CapabilityDescriptor`]); they are
 * keyed by a stable feature id in [`CapabilitiesResponse::runtime_features`].
 */
export type RuntimeFeatureGate = {
/**
 * `true` once the chain has reached the activation height, as sampled by
 * the node against the response's `blockNumber`. An unscheduled feature,
 * or one whose activation height sits in the future, reads `false`.
 */
active: boolean,
/**
 * Height of the milestone that scheduled the feature, or `None` if no
 * milestone has touched the dial. May sit in the future relative to the
 * sampled height (then `active` is `false`).
 */
activationHeight: bigint | null, };
