// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `lyth_getStorageProof` batch response.
 */
export type StorageProofBatch = {
/**
 * State-root the proofs verify against.
 */
stateRoot: string,
/**
 * Block height the proofs were generated against.
 */
blockNumber: bigint,
/**
 * One opaque proof envelope per requested slot.
 */
proofs: unknown[], };
