// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `eth_syncing` response when the node is mid-sync. Returns `false`
 * when the node is caught up — the SDK surfaces that as
 * `Option::None`.
 */
export type SyncStatus = { 
/**
 * First block of the current sync batch.
 */
startingBlock: string, 
/**
 * Last block applied locally.
 */
currentBlock: string, 
/**
 * Highest block advertised by peers.
 */
highestBlock: string, };
