// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Native MRC identity attached to a token-balance row.
 */
export type TokenBalanceMrcIdentity = {
/**
 * MRC standard, currently `mrc20`, `mrc721`, or `mrc1155`.
 */
standard: string,
/**
 * MRC asset id, or collection id for token-specific standards.
 */
assetId: string,
/**
 * Token id inside the collection for MRC-721/MRC-1155 rows.
 */
tokenId?: string | null, };
