// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Native MRC identity attached to a token-balance row.
 */
export type TokenBalanceMrcIdentity = {
/**
 * MRC standard, currently `mrc20`, `mrc721`, `mrc1155`, or `mrc4626`.
 */
standard: string,
/**
 * MRC asset id, collection id, or MRC-4626 vault id.
 */
assetId: string,
/**
 * Token id inside the collection for MRC-721/MRC-1155 rows; `null` for MRC-20/MRC-4626.
 */
tokenId?: string | null, };
