// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenBalanceMrcIdentity } from "./TokenBalanceMrcIdentity.js";

/**
 * Per-asset balance row surfaced by `lyth_getTokenBalances`.
 */
export type TokenBalanceRecord = {
/**
 * 32-byte token id, `0x`-hex.
 */
tokenId: string,
/**
 * Balance as a decimal string.
 */
balance: string,
/**
 * Block height the balance was last observed at.
 */
updatedAtBlock: bigint,
/**
 * Native MRC identity, when the balance came from a native MRC row.
 */
mrc?: TokenBalanceMrcIdentity | null,
/**
 * Optional single bridge route disclosure associated with this asset row.
 */
bridgeRouteDisclosure?: import("../bridge.js").BridgeRouteDisclosure | null,
/**
 * Optional bridge route disclosures associated with this asset row.
 */
bridgeRouteDisclosures?: import("../bridge.js").BridgeRouteDisclosure[] | null, };
