// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-asset balance row surfaced by `lyth_getTokenBalances`.
 */
export type TokenBalanceRecord = {
/**
 * 32-byte token id, `0x`-hex.
 */
tokenId: string,
/**
 * Balance as a decimal string.
 */
balance: string,
/**
 * Block height the balance was last observed at.
 */
updatedAtBlock: bigint, };
