// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `lyth_getTpmAttestation` response.
 */
export type TpmAttestationResponse = { 
/**
 * 32-byte peer id.
 */
peerId: string, 
/**
 * 32-byte digest over the canonical TPM quote bytes.
 */
quoteDigest: string, 
/**
 * 32-byte EK identifier.
 */
ekId: string, 
/**
 * Block selector echoed by the node.
 */
block: unknown, };
