// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Receipt for a confirmed transaction.
 */
export type TransactionReceipt = {
/**
 * Transaction hash.
 */
tx_hash: string,
/**
 * Block hash that contains the transaction.
 */
block_hash: string,
/**
 * Block height that contains the transaction.
 */
block_number: bigint,
/**
 * Transaction index within the block.
 */
tx_index: number,
/**
 * `1` on success, `0` on revert.
 */
status: number,
/**
 * Execution units consumed by this transaction.
 */
executionUnitsUsed: bigint, };
