// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ethereum-shaped transaction view returned by `eth_getTransactionByHash`.
 */
export type TransactionView = {
/**
 * Transaction hash.
 */
hash: string,
/**
 * Block hash that contains the transaction.
 */
blockHash: string,
/**
 * Block height as a hex quantity.
 */
blockNumber: string,
/**
 * Transaction index as a hex quantity.
 */
transactionIndex: string,
/**
 * Sender address.
 */
from: string,
/**
 * Recipient address, or `null` for contract creation.
 */
to: string | null,
/**
 * Sender nonce as a hex quantity.
 */
nonce: string,
/**
 * Transferred value as a hex quantity.
 */
value: string,
/**
 * Gas limit as a hex quantity.
 */
gas: string,
/**
 * EIP-1559 max fee per gas as a hex quantity.
 */
maxFeePerGas: string,
/**
 * EIP-1559 max priority fee per gas as a hex quantity.
 */
maxPriorityFeePerGas: string,
/**
 * Calldata or deployment bytecode.
 */
input: string,
/**
 * EIP-2718 transaction type. `mono-core` currently renders `"0x2"`.
 */
type: string,
/**
 * Chain id as a hex quantity.
 */
chainId: string, };
