// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Discriminated `lyth_txStatus` response.
 */
export type TxStatusResponse = { "status": "found", txHash: string, blockHash: string, blockNumber: bigint, txIndex: number, } | { "status": "not_found", txHash: string, latestHeight: bigint, indexerEnabled: boolean, providerKind: string, };
