// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `lyth_validatorSet` entry.
 */
export type ValidatorDescriptor = {
/**
 * Stable slot id.
 */
id: number,
/**
 * Quantum-safe ML-DSA-65 public key, `0x` hex.
 */
pubkey: string,
/**
 * Stake as a decimal string.
 */
stake: string,
/**
 * Whether the validator can currently propose / vote.
 */
active: boolean, };
