// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VertexAtRound } from "./VertexAtRound.js";

/**
 * `lyth_verticesAtRound` response.
 */
export type VerticesAtRoundResponse = { schemaVersion: number, round: bigint, vertices: Array<VertexAtRound> | null, };
