// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One vertex authorship row in `lyth_verticesAtRound`.
 */
export type VertexAtRound = { vertexHash: string, author: bigint, };
