#!/usr/bin/env bash
# Copies the ts-rs-generated bindings from the Rust crate into the TS
# package's `src/bindings/` directory. Run this whenever the Rust types
# change.
#
# Usage:
#   bash packages/ts/scripts/sync-bindings.sh

set -euo pipefail

repo_root=$(cd "$(dirname "$0")/../../.." && pwd)
rust_bindings="$repo_root/crates/core-sdk/bindings"
ts_bindings="$repo_root/packages/ts/src/bindings"

if [ ! -d "$rust_bindings" ]; then
  echo "error: $rust_bindings does not exist." >&2
  echo "run \`cargo test --features ts-bindings\` first." >&2
  exit 1
fi

mkdir -p "$ts_bindings"

# Wipe stale bindings, copy fresh ones.
find "$ts_bindings" -name '*.ts' -delete
cp "$rust_bindings"/*.ts "$ts_bindings"/

# Regenerate the index re-export.
{
  echo "// This file is auto-generated by sync-bindings.sh. Do not edit."
  echo "// Source: crates/core-sdk/bindings/ (ts-rs)"
  echo
  for f in "$ts_bindings"/*.ts; do
    name=$(basename "$f" .ts)
    if [ "$name" != "index" ]; then
      echo "export type { $name } from \"./${name}.js\";"
    fi
  done
} > "$ts_bindings/index.ts"

count=$(find "$ts_bindings" -name '*.ts' -not -name index.ts | wc -l | tr -d ' ')
echo "synced $count binding files into $ts_bindings"
