/**
 * Official TypeScript SDK for Monolythium v4.1 / LythiumDAG-BFT.
 *
 * The wire types in `./bindings/` are generated from Rust by
 * `cargo test --features ts-bindings`; never edit them by hand. The
 * `RpcClient` mirrors the Rust SDK 1:1 across current `lyth_*` native methods,
 * passive compatibility reads, and server-gated legacy/debug methods.
 *
 * Optional compatibility adapters live under the explicit `./ethers`
 * subpath so native SDK consumers do not import that peer dependency.
 */

export const version = "0.2.2";

export { ApiClient, apiEndpointFromRpcEndpoint } from "./api.js";
export {
  BRIDGE_QUOTE_API_BLOCKED_REASON,
  BRIDGE_REVERT_TAGS,
  BRIDGE_SELECTORS,
  BRIDGE_SUBMIT_API_BLOCKED_REASON,
  V1_BRIDGE_ALLOWED_FEE_TOKEN,
  V1_BRIDGE_ALLOWED_PROTOCOL,
  BridgePrecompileError,
  BridgeRouteCatalogueError,
  assessBridgeRoute,
  bridgeAddressHex,
  bridgeQuoteSubmitReadiness,
  bridgeRoutesReadiness,
  bridgeTransferCandidates,
  buildBridgeRouteCatalogue,
  encodeLockBridgeConfigCalldata,
  encodeSetBridgeRouteFinalityCalldata,
  encodeSetBridgeResumeCooldownCalldata,
  exportBridgeRouteCatalogueJson,
  isBridgeAdminLockedRevert,
  isBridgeCooldownZeroRevert,
  isBridgeFinalityZeroRevert,
  isBridgeResumeCooldownActiveRevert,
  normalizeBridgeRouteCatalogue,
  parseBridgeRouteCatalogueJson,
  rankBridgeRoutes,
  selectBridgeTransferRoute,
  validateBridgeRouteCatalogue,
} from "./bridge.js";
export type {
  BridgeAdminControl,
  BridgeBytesInput,
  BridgeCircuitBreakerState,
  BridgeQuoteSubmitReadiness,
  BridgeRiskTier,
  BridgeRouteAssessment,
  BridgeRouteCandidate,
  BridgeRouteCatalogue,
  BridgeRouteCatalogueJsonOptions,
  BridgeRouteCataloguePayload,
  BridgeRouteCatalogueRoute,
  BridgeRouteCatalogueValidation,
  BridgeRouteDisclosure,
  BridgeRouteSelection,
  BridgeRoutesRequest,
  BridgeRoutesResponse,
  BridgeRoutesSource,
  BridgeTransferIntent,
  BridgeTransferRequest,
  BridgeVerifierDisclosure,
  RankedBridgeRoute,
} from "./bridge.js";
export type {
  ApiAddressActivityData,
  ApiAddressActivityEntry,
  ApiAddressActivityKind,
  ApiAddressActivityKindData,
  ApiAddressActivityKindSummary,
  ApiBlockData,
  ApiBlockHeader,
  ApiBlockTransactionsData,
  ApiCapabilitiesResponse,
  ApiClientOptions,
  ApiClusterData,
  ApiClusterDirectoryEntry,
  ApiClusterDirectoryPage,
  ApiClusterMember,
  ApiClustersData,
  ApiClusterStatus,
  ApiEnvelope,
  ApiErrorEnvelope,
  ApiHealthResponse,
  ApiIndexerStatus,
  ApiLatestAnchor,
  ApiLogEntry,
  ApiOperatorData,
  ApiOperatorInfo,
  ApiQueryValue,
  ApiRuntimeProvenanceData,
  ApiServiceProbeData,
  ApiTransactionData,
  ApiTransactionNativeReceiptData,
  ApiTransactionReceipt,
  ApiTransactionReceiptData,
  ApiTransactionView,
  ApiUpgradePlanStatus,
  ApiUpgradeStatus,
  ApiUpgradeStatusData,
} from "./api.js";
export {
  MAX_NATIVE_RECEIPT_EVENTS,
  RpcClient,
  decodeNativeAgentStateResponse,
  decodeNativeReceiptResponse,
  decodeTxFeedResponse,
  nativeAgentStateFilterParams,
  nativeMarketStateFilterParams,
  nativeEventsFilterParams,
  parseQuantity,
  parseQuantityBig,
} from "./client.js";
export type {
  AddressActivityKind,
  AddressFlowResponse,
  AddressProfileResponse,
  AgentReputationCategoryScope,
  AgentReputationRecord,
  AgentReputationResponse,
  AttestationWindow,
  ChainStatsResponse,
  ClobMarketsResponse,
  ClobMarketSummary,
  ClobOhlcResponse,
  ClobOrderBookResponse,
  ClobTrade,
  ClobTradesResponse,
  ClusterDirectoryEntryResponse,
  ClusterDirectoryPageResponse,
  ClusterMemberResponse,
  ClusterStatusResponse,
  DutyAbsence,
  ExecutionUnitPriceResponse,
  JailStatusWindow,
  KeyRotationWindow,
  LythUpgradePlanStatus,
  LythUpgradeStatusResponse,
  MetricsRangeResponse,
  MetricsRangeSample,
  MetricsRangeSeries,
  MetricsRangeStatus,
  NoEvmArchiveProof,
  NoEvmArchiveCoveringSnapshot,
  NoEvmFinalityCertificate,
  NoEvmFinalityBlockReference,
  NoEvmFinalityEvidence,
  NoEvmReceiptProof,
  NativeReceiptCounters,
  NativeReceiptEvent,
  NativeReceiptFee,
  NativeReceiptResponse,
  NativeReceiptSource,
  NativeEventsFilter,
  NativeEventsResponse,
  NativeEventsResponseFilters,
  NativeEventsSource,
  NativeAgentArbiterStateRecord,
  NativeAgentAttestationStateRecord,
  NativeAgentAvailabilityStateRecord,
  NativeAgentConsentStateRecord,
  NativeAgentEscrowStateRecord,
  NativeAgentIssuerStateRecord,
  NativeAgentPolicySpendStateRecord,
  NativeAgentPolicyStateRecord,
  NativeAgentReputationReviewStateRecord,
  NativeAgentServiceStateRecord,
  NativeAgentStateFilterParamValue,
  NativeAgentStateFilter,
  NativeAgentStateResponse,
  NativeAgentStateResponseFilters,
  NativeAgentStateSource,
  NativeCollectionRoyaltyStateRecord,
  NativeMarketStateFilterParamValue,
  NativeMarketStateFilter,
  NativeMarketStateResponse,
  NativeMarketStateResponseFilters,
  NativeMarketStateSource,
  NativeNftListingStateRecord,
  NativeSpotMarketStateRecord,
  NativeSpotOrderStateRecord,
  NetworkClientOptions,
  OperatorAuthorityResponse,
  OperatorCapabilitiesResponse,
  OperatorInfoResponse,
  OperatorRiskResponse,
  OperatorSigningActivityResponse,
  OperatorSigningEntry,
  OperatorSurfaceCapability,
  OperatorSurfaceStatus,
  PeerSummaryAggregate,
  PrecompileCatalogueResponse,
  RpcClientOptions,
  RuntimeBuildProvenance,
  RuntimeProvenanceResponse,
  RuntimeUpgradeStatus,
  ReportServiceProbeRequest,
  ReportServiceProbeResponse,
  ServiceProbeResponse,
  ServiceProbeStatusLabel,
  SigningEntryStatus,
  SearchHit,
  SearchResponse,
  TxFeedReceipt,
  TxFeedResponse,
  TxFeedTransaction,
  TxStatusFoundResponse,
  TxStatusNotFoundResponse,
  TxStatusResponse,
  UpcomingDutiesResponse,
  UpcomingDutyMap,
  UserAddressInput,
  VertexAtRound,
  VerticesAtRoundResponse,
} from "./client.js";
export {
  API_STREAM_TOPICS,
  NATIVE_MARKET_ORDER_BOOK_STREAM_TOPIC,
  assertNativeMarketOrderBookStreamPayload,
  decodeNativeMarketOrderBookDeltasResponse,
  isNativeMarketOrderBookStreamPayload,
} from "./streams.js";
export type {
  ApiStreamTopic,
  ApiStreamTopicMetadata,
  ApiStreamTopicRetention,
  ApiStreamsIndexResponse,
  NativeMarketOrderBookDelta,
  NativeMarketOrderBookDeltasRequest,
  NativeMarketOrderBookDeltasResponse,
  NativeMarketOrderBookDeltasResponseFilters,
  NativeMarketOrderBookDeltasSource,
  NativeMarketOrderBookStreamAction,
  NativeMarketOrderBookStreamPayload,
} from "./streams.js";
export {
  NO_EVM_ARCHIVE_PROOF_SCHEMA,
  NO_EVM_ARCHIVE_SIGNATURE_SCHEME,
  NO_EVM_FINALITY_EVIDENCE_SCHEMA,
  NO_EVM_FINALITY_EVIDENCE_SOURCE,
  NO_EVM_RECEIPTS_ROOT_DOMAIN,
  NO_EVM_RECEIPT_CODEC,
  NO_EVM_RECEIPT_PROOF_SCHEMA,
  NO_EVM_RECEIPT_PROOF_TYPE,
  NO_EVM_RECEIPT_ROOT_ALGORITHM,
  NoEvmReceiptProofError,
  computeNoEvmDacFinalityMessage,
  computeNoEvmLeaderFinalityMessage,
  computeNoEvmReceiptsRoot,
  computeNoEvmRoundFinalityMessage,
  computeNoEvmTargetReceiptHash,
  decodeNoEvmReceiptTranscript,
  verifyNoEvmBlockFinalityEvidenceMultisig,
  verifyNoEvmBlockFinalityEvidenceThreshold,
  verifyNoEvmFinalityEvidenceMultisig,
  verifyNoEvmFinalityEvidenceThreshold,
  verifyNoEvmArchiveProofSignatures,
  verifyNoEvmReceiptProof,
  verifyNoEvmReceiptProofTrust,
} from "./receipt-proof.js";
export type {
  NoEvmBlockBlsFinalityVerification,
  NoEvmBlsFinalityVerification,
  NoEvmArchiveSignatureVerification,
  NoEvmArchiveSignatureVerificationIssue,
  NoEvmArchiveSignatureVerificationIssueCode,
  NoEvmArchiveTrustedSigner,
  NoEvmReceiptFinalityTrustPolicy,
  NoEvmReceiptProofErrorCode,
  NoEvmReceiptProofVerification,
  NoEvmReceiptTrustIssue,
  NoEvmReceiptTrustIssueCode,
  NoEvmReceiptTrustPolicy,
  NoEvmReceiptTrustVerification,
  NoEvmReceiptTrustedBlsSigner,
} from "./receipt-proof.js";
export {
  NATIVE_MARKET_EVENT_FAMILY,
  consumeNativeEvents,
  isNativeDecodedEvent,
  nativeMarketEventFilter,
  nativeMarketEventsFromHistory,
  nativeMarketEventsFromReceipt,
  nativeEventMatches,
  nativeEventsFromHistory,
  nativeEventsFromReceipt,
  parseNativeDecodedEvent,
} from "./native-events.js";
export type {
  NativeDecodedEvent,
  NativeEventProjection,
  NativeEventConsumer,
  NativeEventFilter,
  NativeMrcPolicyProjection,
  TypedNativeReceiptEvent,
} from "./native-events.js";
export type { ClobMarketRecord } from "./bindings/ClobMarketRecord.js";
export type { ClobMarketResponse } from "./bindings/ClobMarketResponse.js";
export type { MrcAccountRecord } from "./bindings/MrcAccountRecord.js";
export type { MrcAccountRequest } from "./bindings/MrcAccountRequest.js";
export type { MrcAccountResponse } from "./bindings/MrcAccountResponse.js";
export type { MrcHoldersRequest } from "./bindings/MrcHoldersRequest.js";
export type { MrcHoldersResponse } from "./bindings/MrcHoldersResponse.js";
export type { MrcMetadataRecord } from "./bindings/MrcMetadataRecord.js";
export type { MrcMetadataResponse } from "./bindings/MrcMetadataResponse.js";
export type { MrcPolicyRecord } from "./bindings/MrcPolicyRecord.js";
export type { MrcPolicySpendRecord } from "./bindings/MrcPolicySpendRecord.js";
export type { RedemptionQueueResponse } from "./bindings/RedemptionQueueResponse.js";
export type { RedemptionQueueTicket } from "./bindings/RedemptionQueueTicket.js";
export * from "./native-dev.js";
export * from "./mrv.js";
export {
  CHAIN_REGISTRY,
  CHAIN_REGISTRY_RAW_BASE,
  TESTNET_69420,
  fetchChainInfoLatest,
  fetchChainRegistryLatest,
  getChainInfo,
  getNoEvmReceiptTrustPolicy,
  getP2pSeeds,
  getRpcEndpoints,
  noEvmReceiptTrustPolicyFromChainInfo,
  parseChainRegistryToml,
} from "./registry.js";
export type {
  ChainInfo,
  ChainRegistry,
  ExplorerEndpoint,
  NetworkSlug,
  P2pSeed,
  ReceiptProofTrustArchivePolicy,
  ReceiptProofTrustArchiveSigner,
  ReceiptProofTrustFinalityPolicy,
  ReceiptProofTrustFinalitySigner,
  ReceiptProofTrustPolicy,
  RpcEndpoint,
} from "./registry.js";
export { SdkError } from "./error.js";
export * from "./types.js";
export { BURN_ADDR, PRECOMPILE_ADDRESSES } from "./consts.js";
export type { PrecompileName, PrecompileAddress } from "./consts.js";
export {
  NODE_REGISTRY_CAPABILITIES,
  NODE_REGISTRY_CAPABILITY_MASK,
  NODE_REGISTRY_PUBLIC_SERVICE_MASK,
  NODE_REGISTRY_SELECTORS,
  NodeRegistryError,
  SERVICE_PROBE_STATUS,
  encodeReportServiceProbeCalldata,
  isConcreteServiceProbeStatus,
  isSinglePublicServiceProbeMask,
  isValidNodeRegistryCapabilities,
  isValidPublicServiceProbeMask,
  nodeRegistryAddressHex,
  serviceProbeStatusLabel,
} from "./node-registry.js";
export type { ReportServiceProbeCalldataArgs } from "./node-registry.js";
export {
  ADDRESS_KIND_HRPS,
  ADDRESS_HRP,
  RESERVED_ADDRESS_HRPS,
  AddressError,
  addressBytesToHex,
  addressToBech32,
  addressToTypedBech32,
  bech32ToAddress,
  bech32ToAddressBytes,
  hexToAddressBytes,
  normalizeAddressHex,
  parseAddress,
  requireTypedAddress,
  typedBech32ToAddress,
  validateAddress,
} from "./address.js";
export type { AddressKind, AddressValidation, TypedAddress } from "./address.js";
export {
  DELEGATION_REVERT_TAGS,
  DELEGATION_SELECTORS,
  DelegationPrecompileError,
  delegationAddressHex,
  encodeClaimCalldata,
  encodeCompleteRedemptionCalldata,
  encodeDelegateCalldata,
  encodeRedelegateCalldata,
  encodeSetAutoCompoundCalldata,
  encodeUndelegateCalldata,
  isRedemptionPrincipalUnavailableRevert,
} from "./delegation.js";
export {
  ML_DSA_65_PUBLIC_KEY_LEN,
  ML_DSA_65_SIGNATURE_LEN,
  SET_POLICY_CLAIM_DOMAIN_TAG,
  SPENDING_POLICY_SELECTORS,
  SpendingPolicyError,
  composeClaimBoundMessage,
  encodeClaimPolicyByAddressCalldata,
  encodeDisableCalldata,
  encodeEnableCalldata,
  encodeSetPolicyCalldata,
  encodeSetPolicyClaimCalldata,
  spendingPolicyAddressHex,
} from "./spending-policy.js";
export type { SpendingPolicyArgs } from "./spending-policy.js";
export {
  PUBKEY_REGISTRY_ML_DSA_65_PUBLIC_KEY_LEN,
  PUBKEY_REGISTRY_SELECTORS,
  PubkeyRegistryError,
  decodeHasPubkeyReturn,
  decodeLookupPubkeyReturn,
  encodeHasPubkeyCalldata,
  encodeLookupPubkeyCalldata,
  encodeRegisterPubkeyCalldata,
  pubkeyRegistryAddressHex,
} from "./pubkey-registry.js";
export type { PubkeyLookup } from "./pubkey-registry.js";
export {
  CLOB_MARKET_ID_DOMAIN_TAG,
  CLOB_SELECTORS,
  MarketActionError,
  MAX_NATIVE_CALL_FORWARDER_REQUEST_BYTES,
  NATIVE_CALL_FORWARDER_ARTIFACT_PROFILE,
  NATIVE_CALL_FORWARDER_RESPONSE_CAPACITY,
  NATIVE_CALL_FORWARDER_RESPONSE_OFFSET,
  NATIVE_MARKET_MODULE_ADDRESS,
  NATIVE_MARKET_MODULE_ADDRESS_BYTES,
  buildNativeCallForwarderArtifact,
  buildNativeMarketModuleCallEnvelope,
  buildNativeNftBuyListingModuleCall,
  buildNativeNftBuyListingForwarderInput,
  buildNativeNftCancelListingModuleCall,
  buildNativeNftCancelListingForwarderInput,
  buildNativeNftCreateListingModuleCall,
  buildNativeNftCreateListingForwarderInput,
  buildNativeNftPlaceAuctionBidModuleCall,
  buildNativeNftPlaceAuctionBidForwarderInput,
  buildNativeNftSettleAuctionModuleCall,
  buildNativeNftSettleAuctionForwarderInput,
  buildNativeNftSweepExpiredListingsModuleCall,
  buildNativeNftSweepExpiredListingsForwarderInput,
  buildNativeSpotCancelOrderModuleCall,
  buildNativeSpotCancelOrderForwarderInput,
  buildNativeSpotCreateMarketModuleCall,
  buildNativeSpotCreateMarketForwarderInput,
  buildNativeSpotLimitOrderModuleCall,
  buildNativeSpotLimitOrderForwarderInput,
  buildNativeSpotSettleLimitOrderModuleCall,
  buildNativeSpotSettleLimitOrderForwarderInput,
  buildNativeSpotSettleRoutedLimitOrderModuleCall,
  buildNativeSpotSettleRoutedLimitOrderForwarderInput,
  buildCancelSpotOrderPlan,
  buildPlaceSpotLimitOrderPlan,
  buildPlaceSpotMarketOrderExPlan,
  buildPlaceSpotMarketOrderPlan,
  clobAddressHex,
  deriveClobMarketId,
  deriveNativeSpotMarketId,
  deriveNativeSpotOrderId,
  encodeCancelOrderCalldata,
  encodeSetLotSizeCalldata,
  encodeSetMinNotionalCalldata,
  encodeSetTickSizeCalldata,
  encodeNativeMarketModuleForwarderInput,
  encodeNativeNftBuyListingCall,
  encodeNativeNftCancelListingCall,
  encodeNativeNftCreateListingCall,
  encodeNativeNftPlaceAuctionBidCall,
  encodeNativeNftSettleAuctionCall,
  encodeNativeNftSweepExpiredListingsCall,
  encodeNativeSpotCancelOrderCall,
  encodeNativeSpotCreateMarketCall,
  encodeNativeSpotLimitOrderCall,
  encodeNativeSpotSettleLimitOrderCall,
  encodeNativeSpotSettleRoutedLimitOrderCall,
  encodePlaceLimitOrderCalldata,
  encodePlaceMarketOrderCalldata,
  encodePlaceMarketOrderExCalldata,
} from "./market-actions.js";
export type {
  CancelSpotOrderArgs,
  EncodeNativeNftBuyListingArgs,
  EncodeNativeNftCancelListingArgs,
  EncodeNativeNftCreateListingArgs,
  EncodeNativeNftPlaceAuctionBidArgs,
  EncodeNativeNftSettleAuctionArgs,
  EncodeNativeNftSweepExpiredListingsArgs,
  EncodeNativeSpotCancelOrderArgs,
  EncodeNativeSpotCreateMarketArgs,
  EncodeNativeSpotLimitOrderArgs,
  EncodeNativeSpotSettleLimitOrderArgs,
  EncodeNativeSpotSettleRoutedLimitOrderArgs,
  EthSendTransactionRequest,
  MarketTransactionPlan,
  NativeCallForwarderArtifact,
  NativeMarketAddressInput,
  NativeMarketAddressKind,
  NativeMarketForwarderInput,
  NativeMarketModuleCallEnvelope,
  NativeMarketModuleContractCall,
  NativeNftAssetStandard,
  NativeNftListingKind,
  PlaceSpotLimitOrderArgs,
  PlaceSpotMarketOrderArgs,
  PlaceSpotMarketOrderExArgs,
  SpotLimitOrderSide,
  SpotMarketOrderMode,
} from "./market-actions.js";
export {
  AgentActionError,
  NATIVE_AGENT_MODULE_ADDRESS,
  NATIVE_AGENT_MODULE_ADDRESS_BYTES,
  buildNativeAgentCreateEscrowForwarderInput,
  buildNativeAgentCreateEscrowModuleCall,
  buildNativeAgentModuleCallEnvelope,
  buildNativeAgentRecordReputationForwarderInput,
  buildNativeAgentRecordReputationModuleCall,
  buildNativeAgentSetSpendingPolicyForwarderInput,
  buildNativeAgentSetSpendingPolicyModuleCall,
  encodeNativeAgentAcceptEscrowCall,
  encodeNativeAgentApproveEscrowCall,
  encodeNativeAgentArbiterGetCall,
  encodeNativeAgentAttestationGetCall,
  encodeNativeAgentAvailabilityGetCall,
  encodeNativeAgentCancelEscrowCall,
  encodeNativeAgentCloseAvailabilityCall,
  encodeNativeAgentConsentGetCall,
  encodeNativeAgentCounterEscrowCall,
  encodeNativeAgentCreateEscrowCall,
  encodeNativeAgentDeactivateServiceCall,
  encodeNativeAgentDisputeEscrowCall,
  encodeNativeAgentEscrowGetCall,
  encodeNativeAgentGrantConsentCall,
  encodeNativeAgentIssueAttestationCall,
  encodeNativeAgentIssuerGetCall,
  encodeNativeAgentListServiceCall,
  encodeNativeAgentModuleForwarderInput,
  encodeNativeAgentOpenAvailabilityCall,
  encodeNativeAgentRecordPolicySpendCall,
  encodeNativeAgentRecordReputationCall,
  encodeNativeAgentRegisterArbiterCall,
  encodeNativeAgentRegisterIssuerCall,
  encodeNativeAgentReputationGetCall,
  encodeNativeAgentResolveEscrowCall,
  encodeNativeAgentRevokeAttestationCall,
  encodeNativeAgentRevokeConsentCall,
  encodeNativeAgentServiceGetCall,
  encodeNativeAgentSetAvailabilityCall,
  encodeNativeAgentSetSpendingPolicyCall,
  encodeNativeAgentSpendingPolicyGetCall,
  encodeNativeAgentStartEscrowCall,
  encodeNativeAgentSubmitEscrowCall,
} from "./agent-actions.js";
export type {
  EncodeNativeAgentAvailabilitySlotArgs,
  EncodeNativeAgentCreateEscrowArgs,
  EncodeNativeAgentCounterEscrowArgs,
  EncodeNativeAgentDeactivateServiceArgs,
  EncodeNativeAgentEscrowActorArgs,
  EncodeNativeAgentGrantConsentArgs,
  EncodeNativeAgentIssueAttestationArgs,
  EncodeNativeAgentListServiceArgs,
  EncodeNativeAgentRecordPolicySpendArgs,
  EncodeNativeAgentRecordReputationArgs,
  EncodeNativeAgentRegisterArbiterArgs,
  EncodeNativeAgentRegisterIssuerArgs,
  EncodeNativeAgentResolveEscrowArgs,
  EncodeNativeAgentRevokeAttestationArgs,
  EncodeNativeAgentRevokeConsentArgs,
  EncodeNativeAgentSetAvailabilityArgs,
  EncodeNativeAgentSetSpendingPolicyArgs,
  EncodeNativeAgentStartEscrowArgs,
  EncodeNativeAgentSubmitEscrowArgs,
  NativeAgentAddressInput,
  NativeAgentAddressKind,
  NativeAgentEscrowResolution,
  NativeAgentForwarderInput,
  NativeAgentModuleCallEnvelope,
  NativeAgentModuleContractCall,
  NativeAgentReputationScores,
} from "./agent-actions.js";
export {
  MONOLYTHIUM_NETWORKS,
  MONOLYTHIUM_TESTNET_CHAIN_ID,
  MONOLYTHIUM_TESTNET_NETWORK_NAME,
} from "./network.js";
export type { MonolythiumNetworkConfig } from "./network.js";
